// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: V2C/VehicleMessageHeader.proto

#include "V2C/VehicleMessageHeader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_V2C_2fVehicleMessageHeader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto;
namespace com {
namespace vehicle {
namespace messages {
class VehicleMessageHeaderDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<VehicleMessageHeader> _instance;
} _VehicleMessageHeader_default_instance_;
class lat_longDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<lat_long> _instance;
} _lat_long_default_instance_;
}  // namespace messages
}  // namespace vehicle
}  // namespace com
static void InitDefaultsscc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::vehicle::messages::_VehicleMessageHeader_default_instance_;
    new (ptr) ::com::vehicle::messages::VehicleMessageHeader();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::vehicle::messages::VehicleMessageHeader::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto}, {
      &scc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto.base,}};

static void InitDefaultsscc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::vehicle::messages::_lat_long_default_instance_;
    new (ptr) ::com::vehicle::messages::lat_long();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::vehicle::messages::lat_long::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_V2C_2fVehicleMessageHeader_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_V2C_2fVehicleMessageHeader_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_V2C_2fVehicleMessageHeader_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_V2C_2fVehicleMessageHeader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, message_id_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, correlation_id_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, vehicle_id_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, message_timestamp_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, protocol_version_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::VehicleMessageHeader, location_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::lat_long, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::lat_long, latitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::lat_long, longitude_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::com::vehicle::messages::VehicleMessageHeader)},
  { 11, -1, sizeof(::com::vehicle::messages::lat_long)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::vehicle::messages::_VehicleMessageHeader_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::vehicle::messages::_lat_long_default_instance_),
};

const char descriptor_table_protodef_V2C_2fVehicleMessageHeader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\036V2C/VehicleMessageHeader.proto\022\024com.ve"
  "hicle.messages\"\275\001\n\024VehicleMessageHeader\022"
  "\022\n\nmessage_id\030\001 \001(\005\022\026\n\016correlation_id\030\002 "
  "\001(\005\022\022\n\nvehicle_id\030\003 \001(\t\022\031\n\021message_times"
  "tamp\030\004 \001(\003\022\030\n\020protocol_version\030\005 \001(\001\0220\n\010"
  "location\030\006 \001(\0132\036.com.vehicle.messages.la"
  "t_long\"/\n\010lat_long\022\020\n\010latitude\030\001 \001(\001\022\021\n\t"
  "longitude\030\002 \001(\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_V2C_2fVehicleMessageHeader_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_V2C_2fVehicleMessageHeader_2eproto_sccs[2] = {
  &scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto.base,
  &scc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_V2C_2fVehicleMessageHeader_2eproto_once;
static bool descriptor_table_V2C_2fVehicleMessageHeader_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_V2C_2fVehicleMessageHeader_2eproto = {
  &descriptor_table_V2C_2fVehicleMessageHeader_2eproto_initialized, descriptor_table_protodef_V2C_2fVehicleMessageHeader_2eproto, "V2C/VehicleMessageHeader.proto", 303,
  &descriptor_table_V2C_2fVehicleMessageHeader_2eproto_once, descriptor_table_V2C_2fVehicleMessageHeader_2eproto_sccs, descriptor_table_V2C_2fVehicleMessageHeader_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_V2C_2fVehicleMessageHeader_2eproto::offsets,
  file_level_metadata_V2C_2fVehicleMessageHeader_2eproto, 2, file_level_enum_descriptors_V2C_2fVehicleMessageHeader_2eproto, file_level_service_descriptors_V2C_2fVehicleMessageHeader_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_V2C_2fVehicleMessageHeader_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_V2C_2fVehicleMessageHeader_2eproto), true);
namespace com {
namespace vehicle {
namespace messages {

// ===================================================================

void VehicleMessageHeader::InitAsDefaultInstance() {
  ::com::vehicle::messages::_VehicleMessageHeader_default_instance_._instance.get_mutable()->location_ = const_cast< ::com::vehicle::messages::lat_long*>(
      ::com::vehicle::messages::lat_long::internal_default_instance());
}
class VehicleMessageHeader::_Internal {
 public:
  static const ::com::vehicle::messages::lat_long& location(const VehicleMessageHeader* msg);
};

const ::com::vehicle::messages::lat_long&
VehicleMessageHeader::_Internal::location(const VehicleMessageHeader* msg) {
  return *msg->location_;
}
VehicleMessageHeader::VehicleMessageHeader()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vehicle.messages.VehicleMessageHeader)
}
VehicleMessageHeader::VehicleMessageHeader(const VehicleMessageHeader& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  vehicle_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_vehicle_id().empty()) {
    vehicle_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.vehicle_id_);
  }
  if (from._internal_has_location()) {
    location_ = new ::com::vehicle::messages::lat_long(*from.location_);
  } else {
    location_ = nullptr;
  }
  ::memcpy(&message_id_, &from.message_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&protocol_version_) -
    reinterpret_cast<char*>(&message_id_)) + sizeof(protocol_version_));
  // @@protoc_insertion_point(copy_constructor:com.vehicle.messages.VehicleMessageHeader)
}

void VehicleMessageHeader::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto.base);
  vehicle_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&location_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&protocol_version_) -
      reinterpret_cast<char*>(&location_)) + sizeof(protocol_version_));
}

VehicleMessageHeader::~VehicleMessageHeader() {
  // @@protoc_insertion_point(destructor:com.vehicle.messages.VehicleMessageHeader)
  SharedDtor();
}

void VehicleMessageHeader::SharedDtor() {
  vehicle_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete location_;
}

void VehicleMessageHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VehicleMessageHeader& VehicleMessageHeader::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto.base);
  return *internal_default_instance();
}


void VehicleMessageHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vehicle.messages.VehicleMessageHeader)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vehicle_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && location_ != nullptr) {
    delete location_;
  }
  location_ = nullptr;
  ::memset(&message_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&protocol_version_) -
      reinterpret_cast<char*>(&message_id_)) + sizeof(protocol_version_));
  _internal_metadata_.Clear();
}

const char* VehicleMessageHeader::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 message_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          message_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 correlation_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          correlation_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string vehicle_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_vehicle_id(), ptr, ctx, "com.vehicle.messages.VehicleMessageHeader.vehicle_id");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 message_timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          message_timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double protocol_version = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          protocol_version_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // .com.vehicle.messages.lat_long location = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_location(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* VehicleMessageHeader::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vehicle.messages.VehicleMessageHeader)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_message_id(), target);
  }

  // int32 correlation_id = 2;
  if (this->correlation_id() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_correlation_id(), target);
  }

  // string vehicle_id = 3;
  if (this->vehicle_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_vehicle_id().data(), static_cast<int>(this->_internal_vehicle_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.vehicle.messages.VehicleMessageHeader.vehicle_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_vehicle_id(), target);
  }

  // int64 message_timestamp = 4;
  if (this->message_timestamp() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_message_timestamp(), target);
  }

  // double protocol_version = 5;
  if (!(this->protocol_version() <= 0 && this->protocol_version() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_protocol_version(), target);
  }

  // .com.vehicle.messages.lat_long location = 6;
  if (this->has_location()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, _Internal::location(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.vehicle.messages.VehicleMessageHeader)
  return target;
}

size_t VehicleMessageHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vehicle.messages.VehicleMessageHeader)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string vehicle_id = 3;
  if (this->vehicle_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_vehicle_id());
  }

  // .com.vehicle.messages.lat_long location = 6;
  if (this->has_location()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *location_);
  }

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_message_id());
  }

  // int32 correlation_id = 2;
  if (this->correlation_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_correlation_id());
  }

  // int64 message_timestamp = 4;
  if (this->message_timestamp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_message_timestamp());
  }

  // double protocol_version = 5;
  if (!(this->protocol_version() <= 0 && this->protocol_version() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VehicleMessageHeader::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vehicle.messages.VehicleMessageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const VehicleMessageHeader* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<VehicleMessageHeader>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vehicle.messages.VehicleMessageHeader)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vehicle.messages.VehicleMessageHeader)
    MergeFrom(*source);
  }
}

void VehicleMessageHeader::MergeFrom(const VehicleMessageHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vehicle.messages.VehicleMessageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.vehicle_id().size() > 0) {

    vehicle_id_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.vehicle_id_);
  }
  if (from.has_location()) {
    _internal_mutable_location()->::com::vehicle::messages::lat_long::MergeFrom(from._internal_location());
  }
  if (from.message_id() != 0) {
    _internal_set_message_id(from._internal_message_id());
  }
  if (from.correlation_id() != 0) {
    _internal_set_correlation_id(from._internal_correlation_id());
  }
  if (from.message_timestamp() != 0) {
    _internal_set_message_timestamp(from._internal_message_timestamp());
  }
  if (!(from.protocol_version() <= 0 && from.protocol_version() >= 0)) {
    _internal_set_protocol_version(from._internal_protocol_version());
  }
}

void VehicleMessageHeader::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vehicle.messages.VehicleMessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VehicleMessageHeader::CopyFrom(const VehicleMessageHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vehicle.messages.VehicleMessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VehicleMessageHeader::IsInitialized() const {
  return true;
}

void VehicleMessageHeader::InternalSwap(VehicleMessageHeader* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  vehicle_id_.Swap(&other->vehicle_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(location_, other->location_);
  swap(message_id_, other->message_id_);
  swap(correlation_id_, other->correlation_id_);
  swap(message_timestamp_, other->message_timestamp_);
  swap(protocol_version_, other->protocol_version_);
}

::PROTOBUF_NAMESPACE_ID::Metadata VehicleMessageHeader::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void lat_long::InitAsDefaultInstance() {
}
class lat_long::_Internal {
 public:
};

lat_long::lat_long()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vehicle.messages.lat_long)
}
lat_long::lat_long(const lat_long& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&latitude_, &from.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&longitude_) -
    reinterpret_cast<char*>(&latitude_)) + sizeof(longitude_));
  // @@protoc_insertion_point(copy_constructor:com.vehicle.messages.lat_long)
}

void lat_long::SharedCtor() {
  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&longitude_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(longitude_));
}

lat_long::~lat_long() {
  // @@protoc_insertion_point(destructor:com.vehicle.messages.lat_long)
  SharedDtor();
}

void lat_long::SharedDtor() {
}

void lat_long::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const lat_long& lat_long::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_lat_long_V2C_2fVehicleMessageHeader_2eproto.base);
  return *internal_default_instance();
}


void lat_long::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vehicle.messages.lat_long)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&longitude_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(longitude_));
  _internal_metadata_.Clear();
}

const char* lat_long::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double latitude = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double longitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* lat_long::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vehicle.messages.lat_long)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double latitude = 1;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_latitude(), target);
  }

  // double longitude = 2;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_longitude(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.vehicle.messages.lat_long)
  return target;
}

size_t lat_long::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vehicle.messages.lat_long)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double latitude = 1;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    total_size += 1 + 8;
  }

  // double longitude = 2;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void lat_long::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vehicle.messages.lat_long)
  GOOGLE_DCHECK_NE(&from, this);
  const lat_long* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<lat_long>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vehicle.messages.lat_long)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vehicle.messages.lat_long)
    MergeFrom(*source);
  }
}

void lat_long::MergeFrom(const lat_long& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vehicle.messages.lat_long)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.latitude() <= 0 && from.latitude() >= 0)) {
    _internal_set_latitude(from._internal_latitude());
  }
  if (!(from.longitude() <= 0 && from.longitude() >= 0)) {
    _internal_set_longitude(from._internal_longitude());
  }
}

void lat_long::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vehicle.messages.lat_long)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void lat_long::CopyFrom(const lat_long& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vehicle.messages.lat_long)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool lat_long::IsInitialized() const {
  return true;
}

void lat_long::InternalSwap(lat_long* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(latitude_, other->latitude_);
  swap(longitude_, other->longitude_);
}

::PROTOBUF_NAMESPACE_ID::Metadata lat_long::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace vehicle
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::vehicle::messages::VehicleMessageHeader* Arena::CreateMaybeMessage< ::com::vehicle::messages::VehicleMessageHeader >(Arena* arena) {
  return Arena::CreateInternal< ::com::vehicle::messages::VehicleMessageHeader >(arena);
}
template<> PROTOBUF_NOINLINE ::com::vehicle::messages::lat_long* Arena::CreateMaybeMessage< ::com::vehicle::messages::lat_long >(Arena* arena) {
  return Arena::CreateInternal< ::com::vehicle::messages::lat_long >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
