// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: V2C/VehiclePrecisionLocation.proto

#include "V2C/VehiclePrecisionLocation.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_V2C_2fVehiclePrecisionLocation_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_V2C_2fVehicleMessageHeader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto;
namespace com {
namespace vehicle {
namespace messages {
class PublishPreciseVehicleLocationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PublishPreciseVehicleLocation> _instance;
} _PublishPreciseVehicleLocation_default_instance_;
class RequestPreciseVehicleLocationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RequestPreciseVehicleLocation> _instance;
} _RequestPreciseVehicleLocation_default_instance_;
class ResponsePreciseVehicleLocationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResponsePreciseVehicleLocation> _instance;
} _ResponsePreciseVehicleLocation_default_instance_;
class ResponseConditionDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResponseCondition> _instance;
} _ResponseCondition_default_instance_;
}  // namespace messages
}  // namespace vehicle
}  // namespace com
static void InitDefaultsscc_info_PublishPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::vehicle::messages::_PublishPreciseVehicleLocation_default_instance_;
    new (ptr) ::com::vehicle::messages::PublishPreciseVehicleLocation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::vehicle::messages::PublishPreciseVehicleLocation::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PublishPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PublishPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto}, {
      &scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto.base,}};

static void InitDefaultsscc_info_RequestPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::vehicle::messages::_RequestPreciseVehicleLocation_default_instance_;
    new (ptr) ::com::vehicle::messages::RequestPreciseVehicleLocation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::vehicle::messages::RequestPreciseVehicleLocation::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RequestPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RequestPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto}, {
      &scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto.base,}};

static void InitDefaultsscc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::vehicle::messages::_ResponseCondition_default_instance_;
    new (ptr) ::com::vehicle::messages::ResponseCondition();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::vehicle::messages::ResponseCondition::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto}, {}};

static void InitDefaultsscc_info_ResponsePreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::vehicle::messages::_ResponsePreciseVehicleLocation_default_instance_;
    new (ptr) ::com::vehicle::messages::ResponsePreciseVehicleLocation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::vehicle::messages::ResponsePreciseVehicleLocation::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ResponsePreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ResponsePreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto}, {
      &scc_info_VehicleMessageHeader_V2C_2fVehicleMessageHeader_2eproto.base,
      &scc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_V2C_2fVehiclePrecisionLocation_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_V2C_2fVehiclePrecisionLocation_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_V2C_2fVehiclePrecisionLocation_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_V2C_2fVehiclePrecisionLocation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, vehiclemessageheader_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, latitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, longitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, estimated_position_error_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, position_altitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, gps_fix_typeenum_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, is_gps_fix_available_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, estimated_altitude_error_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::PublishPreciseVehicleLocation, position_direction_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::RequestPreciseVehicleLocation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::RequestPreciseVehicleLocation, vehiclemessageheader_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, vehiclemessageheader_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, response_condition_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, latitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, longitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, estimated_position_error_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, position_altitude_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, gps_fix_typeenum_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, is_gps_fix_available_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, estimated_altitude_error_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponsePreciseVehicleLocation, position_direction_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponseCondition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponseCondition, result_),
  PROTOBUF_FIELD_OFFSET(::com::vehicle::messages::ResponseCondition, reason_code_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::com::vehicle::messages::PublishPreciseVehicleLocation)},
  { 14, -1, sizeof(::com::vehicle::messages::RequestPreciseVehicleLocation)},
  { 20, -1, sizeof(::com::vehicle::messages::ResponsePreciseVehicleLocation)},
  { 35, -1, sizeof(::com::vehicle::messages::ResponseCondition)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::vehicle::messages::_PublishPreciseVehicleLocation_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::vehicle::messages::_RequestPreciseVehicleLocation_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::vehicle::messages::_ResponsePreciseVehicleLocation_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::vehicle::messages::_ResponseCondition_default_instance_),
};

const char descriptor_table_protodef_V2C_2fVehiclePrecisionLocation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\"V2C/VehiclePrecisionLocation.proto\022\024co"
  "m.vehicle.messages\032\036V2C/VehicleMessageHe"
  "ader.proto\"\343\002\n\035PublishPreciseVehicleLoca"
  "tion\022H\n\024vehicleMessageHeader\030\001 \001(\0132*.com"
  ".vehicle.messages.VehicleMessageHeader\022\020"
  "\n\010latitude\030\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\022 \n\030e"
  "stimated_position_error\030\005 \001(\005\022\031\n\021positio"
  "n_altitude\030\006 \001(\001\022:\n\020gps_fix_typeEnum\030\007 \001"
  "(\0162 .com.vehicle.messages.gpsFixEnum\022\034\n\024"
  "is_gps_fix_available\030\010 \001(\010\022 \n\030estimated_"
  "altitude_error\030\t \001(\005\022\032\n\022position_directi"
  "on\030\n \001(\001\"i\n\035RequestPreciseVehicleLocatio"
  "n\022H\n\024vehicleMessageHeader\030\001 \001(\0132*.com.ve"
  "hicle.messages.VehicleMessageHeader\"\251\003\n\036"
  "ResponsePreciseVehicleLocation\022H\n\024vehicl"
  "eMessageHeader\030\001 \001(\0132*.com.vehicle.messa"
  "ges.VehicleMessageHeader\022C\n\022response_con"
  "dition\030\002 \001(\0132\'.com.vehicle.messages.Resp"
  "onseCondition\022\020\n\010latitude\030\003 \001(\001\022\021\n\tlongi"
  "tude\030\004 \001(\001\022 \n\030estimated_position_error\030\005"
  " \001(\005\022\031\n\021position_altitude\030\006 \001(\001\022:\n\020gps_f"
  "ix_typeEnum\030\007 \001(\0162 .com.vehicle.messages"
  ".gpsFixEnum\022\034\n\024is_gps_fix_available\030\010 \001("
  "\010\022 \n\030estimated_altitude_error\030\t \001(\005\022\032\n\022p"
  "osition_direction\030\n \001(\001\"\303\001\n\021ResponseCond"
  "ition\022C\n\006result\030\001 \001(\01623.com.vehicle.mess"
  "ages.ResponseCondition.resultsEnum\022\023\n\013re"
  "ason_code\030\002 \001(\t\"T\n\013resultsEnum\022\013\n\007SUCCES"
  "S\020\000\022\027\n\023FAILED_SYSTEM_ERROR\020\001\022\037\n\033FAILED_L"
  "OCATION_UNAVAILABLE\020\002*S\n\ngpsFixEnum\022\021\n\rI"
  "D_FIX_NO_POS\020\000\022\r\n\tID_FIX_3D\020\001\022\r\n\tID_FIX_"
  "2D\020\002\022\024\n\020ID_FIX_ESTIMATED\020\003P\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_deps[1] = {
  &::descriptor_table_V2C_2fVehicleMessageHeader_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_sccs[4] = {
  &scc_info_PublishPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base,
  &scc_info_RequestPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base,
  &scc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto.base,
  &scc_info_ResponsePreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_once;
static bool descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto = {
  &descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_initialized, descriptor_table_protodef_V2C_2fVehiclePrecisionLocation_2eproto, "V2C/VehiclePrecisionLocation.proto", 1276,
  &descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_once, descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_sccs, descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto_deps, 4, 1,
  schemas, file_default_instances, TableStruct_V2C_2fVehiclePrecisionLocation_2eproto::offsets,
  file_level_metadata_V2C_2fVehiclePrecisionLocation_2eproto, 4, file_level_enum_descriptors_V2C_2fVehiclePrecisionLocation_2eproto, file_level_service_descriptors_V2C_2fVehiclePrecisionLocation_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_V2C_2fVehiclePrecisionLocation_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto), true);
namespace com {
namespace vehicle {
namespace messages {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResponseCondition_resultsEnum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto);
  return file_level_enum_descriptors_V2C_2fVehiclePrecisionLocation_2eproto[0];
}
bool ResponseCondition_resultsEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ResponseCondition_resultsEnum ResponseCondition::SUCCESS;
constexpr ResponseCondition_resultsEnum ResponseCondition::FAILED_SYSTEM_ERROR;
constexpr ResponseCondition_resultsEnum ResponseCondition::FAILED_LOCATION_UNAVAILABLE;
constexpr ResponseCondition_resultsEnum ResponseCondition::resultsEnum_MIN;
constexpr ResponseCondition_resultsEnum ResponseCondition::resultsEnum_MAX;
constexpr int ResponseCondition::resultsEnum_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* gpsFixEnum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto);
  return file_level_enum_descriptors_V2C_2fVehiclePrecisionLocation_2eproto[1];
}
bool gpsFixEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void PublishPreciseVehicleLocation::InitAsDefaultInstance() {
  ::com::vehicle::messages::_PublishPreciseVehicleLocation_default_instance_._instance.get_mutable()->vehiclemessageheader_ = const_cast< ::com::vehicle::messages::VehicleMessageHeader*>(
      ::com::vehicle::messages::VehicleMessageHeader::internal_default_instance());
}
class PublishPreciseVehicleLocation::_Internal {
 public:
  static const ::com::vehicle::messages::VehicleMessageHeader& vehiclemessageheader(const PublishPreciseVehicleLocation* msg);
};

const ::com::vehicle::messages::VehicleMessageHeader&
PublishPreciseVehicleLocation::_Internal::vehiclemessageheader(const PublishPreciseVehicleLocation* msg) {
  return *msg->vehiclemessageheader_;
}
void PublishPreciseVehicleLocation::clear_vehiclemessageheader() {
  if (GetArenaNoVirtual() == nullptr && vehiclemessageheader_ != nullptr) {
    delete vehiclemessageheader_;
  }
  vehiclemessageheader_ = nullptr;
}
PublishPreciseVehicleLocation::PublishPreciseVehicleLocation()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vehicle.messages.PublishPreciseVehicleLocation)
}
PublishPreciseVehicleLocation::PublishPreciseVehicleLocation(const PublishPreciseVehicleLocation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_vehiclemessageheader()) {
    vehiclemessageheader_ = new ::com::vehicle::messages::VehicleMessageHeader(*from.vehiclemessageheader_);
  } else {
    vehiclemessageheader_ = nullptr;
  }
  ::memcpy(&latitude_, &from.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&position_direction_) -
    reinterpret_cast<char*>(&latitude_)) + sizeof(position_direction_));
  // @@protoc_insertion_point(copy_constructor:com.vehicle.messages.PublishPreciseVehicleLocation)
}

void PublishPreciseVehicleLocation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PublishPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base);
  ::memset(&vehiclemessageheader_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&position_direction_) -
      reinterpret_cast<char*>(&vehiclemessageheader_)) + sizeof(position_direction_));
}

PublishPreciseVehicleLocation::~PublishPreciseVehicleLocation() {
  // @@protoc_insertion_point(destructor:com.vehicle.messages.PublishPreciseVehicleLocation)
  SharedDtor();
}

void PublishPreciseVehicleLocation::SharedDtor() {
  if (this != internal_default_instance()) delete vehiclemessageheader_;
}

void PublishPreciseVehicleLocation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PublishPreciseVehicleLocation& PublishPreciseVehicleLocation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PublishPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base);
  return *internal_default_instance();
}


void PublishPreciseVehicleLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && vehiclemessageheader_ != nullptr) {
    delete vehiclemessageheader_;
  }
  vehiclemessageheader_ = nullptr;
  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&position_direction_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(position_direction_));
  _internal_metadata_.Clear();
}

const char* PublishPreciseVehicleLocation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_vehiclemessageheader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double latitude = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double longitude = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 estimated_position_error = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          estimated_position_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double position_altitude = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          position_altitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_gps_fix_typeenum(static_cast<::com::vehicle::messages::gpsFixEnum>(val));
        } else goto handle_unusual;
        continue;
      // bool is_gps_fix_available = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          is_gps_fix_available_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 estimated_altitude_error = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          estimated_altitude_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double position_direction = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          position_direction_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PublishPreciseVehicleLocation::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  if (this->has_vehiclemessageheader()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::vehiclemessageheader(this), target, stream);
  }

  // double latitude = 3;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_latitude(), target);
  }

  // double longitude = 4;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_longitude(), target);
  }

  // int32 estimated_position_error = 5;
  if (this->estimated_position_error() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_estimated_position_error(), target);
  }

  // double position_altitude = 6;
  if (!(this->position_altitude() <= 0 && this->position_altitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_position_altitude(), target);
  }

  // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
  if (this->gps_fix_typeenum() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      7, this->_internal_gps_fix_typeenum(), target);
  }

  // bool is_gps_fix_available = 8;
  if (this->is_gps_fix_available() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(8, this->_internal_is_gps_fix_available(), target);
  }

  // int32 estimated_altitude_error = 9;
  if (this->estimated_altitude_error() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_estimated_altitude_error(), target);
  }

  // double position_direction = 10;
  if (!(this->position_direction() <= 0 && this->position_direction() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_position_direction(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.vehicle.messages.PublishPreciseVehicleLocation)
  return target;
}

size_t PublishPreciseVehicleLocation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  if (this->has_vehiclemessageheader()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *vehiclemessageheader_);
  }

  // double latitude = 3;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    total_size += 1 + 8;
  }

  // double longitude = 4;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    total_size += 1 + 8;
  }

  // double position_altitude = 6;
  if (!(this->position_altitude() <= 0 && this->position_altitude() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 estimated_position_error = 5;
  if (this->estimated_position_error() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_estimated_position_error());
  }

  // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
  if (this->gps_fix_typeenum() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_gps_fix_typeenum());
  }

  // bool is_gps_fix_available = 8;
  if (this->is_gps_fix_available() != 0) {
    total_size += 1 + 1;
  }

  // int32 estimated_altitude_error = 9;
  if (this->estimated_altitude_error() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_estimated_altitude_error());
  }

  // double position_direction = 10;
  if (!(this->position_direction() <= 0 && this->position_direction() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PublishPreciseVehicleLocation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  GOOGLE_DCHECK_NE(&from, this);
  const PublishPreciseVehicleLocation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PublishPreciseVehicleLocation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vehicle.messages.PublishPreciseVehicleLocation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vehicle.messages.PublishPreciseVehicleLocation)
    MergeFrom(*source);
  }
}

void PublishPreciseVehicleLocation::MergeFrom(const PublishPreciseVehicleLocation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_vehiclemessageheader()) {
    _internal_mutable_vehiclemessageheader()->::com::vehicle::messages::VehicleMessageHeader::MergeFrom(from._internal_vehiclemessageheader());
  }
  if (!(from.latitude() <= 0 && from.latitude() >= 0)) {
    _internal_set_latitude(from._internal_latitude());
  }
  if (!(from.longitude() <= 0 && from.longitude() >= 0)) {
    _internal_set_longitude(from._internal_longitude());
  }
  if (!(from.position_altitude() <= 0 && from.position_altitude() >= 0)) {
    _internal_set_position_altitude(from._internal_position_altitude());
  }
  if (from.estimated_position_error() != 0) {
    _internal_set_estimated_position_error(from._internal_estimated_position_error());
  }
  if (from.gps_fix_typeenum() != 0) {
    _internal_set_gps_fix_typeenum(from._internal_gps_fix_typeenum());
  }
  if (from.is_gps_fix_available() != 0) {
    _internal_set_is_gps_fix_available(from._internal_is_gps_fix_available());
  }
  if (from.estimated_altitude_error() != 0) {
    _internal_set_estimated_altitude_error(from._internal_estimated_altitude_error());
  }
  if (!(from.position_direction() <= 0 && from.position_direction() >= 0)) {
    _internal_set_position_direction(from._internal_position_direction());
  }
}

void PublishPreciseVehicleLocation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublishPreciseVehicleLocation::CopyFrom(const PublishPreciseVehicleLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vehicle.messages.PublishPreciseVehicleLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublishPreciseVehicleLocation::IsInitialized() const {
  return true;
}

void PublishPreciseVehicleLocation::InternalSwap(PublishPreciseVehicleLocation* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(vehiclemessageheader_, other->vehiclemessageheader_);
  swap(latitude_, other->latitude_);
  swap(longitude_, other->longitude_);
  swap(position_altitude_, other->position_altitude_);
  swap(estimated_position_error_, other->estimated_position_error_);
  swap(gps_fix_typeenum_, other->gps_fix_typeenum_);
  swap(is_gps_fix_available_, other->is_gps_fix_available_);
  swap(estimated_altitude_error_, other->estimated_altitude_error_);
  swap(position_direction_, other->position_direction_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PublishPreciseVehicleLocation::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RequestPreciseVehicleLocation::InitAsDefaultInstance() {
  ::com::vehicle::messages::_RequestPreciseVehicleLocation_default_instance_._instance.get_mutable()->vehiclemessageheader_ = const_cast< ::com::vehicle::messages::VehicleMessageHeader*>(
      ::com::vehicle::messages::VehicleMessageHeader::internal_default_instance());
}
class RequestPreciseVehicleLocation::_Internal {
 public:
  static const ::com::vehicle::messages::VehicleMessageHeader& vehiclemessageheader(const RequestPreciseVehicleLocation* msg);
};

const ::com::vehicle::messages::VehicleMessageHeader&
RequestPreciseVehicleLocation::_Internal::vehiclemessageheader(const RequestPreciseVehicleLocation* msg) {
  return *msg->vehiclemessageheader_;
}
void RequestPreciseVehicleLocation::clear_vehiclemessageheader() {
  if (GetArenaNoVirtual() == nullptr && vehiclemessageheader_ != nullptr) {
    delete vehiclemessageheader_;
  }
  vehiclemessageheader_ = nullptr;
}
RequestPreciseVehicleLocation::RequestPreciseVehicleLocation()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vehicle.messages.RequestPreciseVehicleLocation)
}
RequestPreciseVehicleLocation::RequestPreciseVehicleLocation(const RequestPreciseVehicleLocation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_vehiclemessageheader()) {
    vehiclemessageheader_ = new ::com::vehicle::messages::VehicleMessageHeader(*from.vehiclemessageheader_);
  } else {
    vehiclemessageheader_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:com.vehicle.messages.RequestPreciseVehicleLocation)
}

void RequestPreciseVehicleLocation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RequestPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base);
  vehiclemessageheader_ = nullptr;
}

RequestPreciseVehicleLocation::~RequestPreciseVehicleLocation() {
  // @@protoc_insertion_point(destructor:com.vehicle.messages.RequestPreciseVehicleLocation)
  SharedDtor();
}

void RequestPreciseVehicleLocation::SharedDtor() {
  if (this != internal_default_instance()) delete vehiclemessageheader_;
}

void RequestPreciseVehicleLocation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RequestPreciseVehicleLocation& RequestPreciseVehicleLocation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RequestPreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base);
  return *internal_default_instance();
}


void RequestPreciseVehicleLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && vehiclemessageheader_ != nullptr) {
    delete vehiclemessageheader_;
  }
  vehiclemessageheader_ = nullptr;
  _internal_metadata_.Clear();
}

const char* RequestPreciseVehicleLocation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_vehiclemessageheader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RequestPreciseVehicleLocation::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  if (this->has_vehiclemessageheader()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::vehiclemessageheader(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.vehicle.messages.RequestPreciseVehicleLocation)
  return target;
}

size_t RequestPreciseVehicleLocation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  if (this->has_vehiclemessageheader()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *vehiclemessageheader_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RequestPreciseVehicleLocation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  GOOGLE_DCHECK_NE(&from, this);
  const RequestPreciseVehicleLocation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RequestPreciseVehicleLocation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vehicle.messages.RequestPreciseVehicleLocation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vehicle.messages.RequestPreciseVehicleLocation)
    MergeFrom(*source);
  }
}

void RequestPreciseVehicleLocation::MergeFrom(const RequestPreciseVehicleLocation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_vehiclemessageheader()) {
    _internal_mutable_vehiclemessageheader()->::com::vehicle::messages::VehicleMessageHeader::MergeFrom(from._internal_vehiclemessageheader());
  }
}

void RequestPreciseVehicleLocation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RequestPreciseVehicleLocation::CopyFrom(const RequestPreciseVehicleLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vehicle.messages.RequestPreciseVehicleLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestPreciseVehicleLocation::IsInitialized() const {
  return true;
}

void RequestPreciseVehicleLocation::InternalSwap(RequestPreciseVehicleLocation* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(vehiclemessageheader_, other->vehiclemessageheader_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestPreciseVehicleLocation::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ResponsePreciseVehicleLocation::InitAsDefaultInstance() {
  ::com::vehicle::messages::_ResponsePreciseVehicleLocation_default_instance_._instance.get_mutable()->vehiclemessageheader_ = const_cast< ::com::vehicle::messages::VehicleMessageHeader*>(
      ::com::vehicle::messages::VehicleMessageHeader::internal_default_instance());
  ::com::vehicle::messages::_ResponsePreciseVehicleLocation_default_instance_._instance.get_mutable()->response_condition_ = const_cast< ::com::vehicle::messages::ResponseCondition*>(
      ::com::vehicle::messages::ResponseCondition::internal_default_instance());
}
class ResponsePreciseVehicleLocation::_Internal {
 public:
  static const ::com::vehicle::messages::VehicleMessageHeader& vehiclemessageheader(const ResponsePreciseVehicleLocation* msg);
  static const ::com::vehicle::messages::ResponseCondition& response_condition(const ResponsePreciseVehicleLocation* msg);
};

const ::com::vehicle::messages::VehicleMessageHeader&
ResponsePreciseVehicleLocation::_Internal::vehiclemessageheader(const ResponsePreciseVehicleLocation* msg) {
  return *msg->vehiclemessageheader_;
}
const ::com::vehicle::messages::ResponseCondition&
ResponsePreciseVehicleLocation::_Internal::response_condition(const ResponsePreciseVehicleLocation* msg) {
  return *msg->response_condition_;
}
void ResponsePreciseVehicleLocation::clear_vehiclemessageheader() {
  if (GetArenaNoVirtual() == nullptr && vehiclemessageheader_ != nullptr) {
    delete vehiclemessageheader_;
  }
  vehiclemessageheader_ = nullptr;
}
ResponsePreciseVehicleLocation::ResponsePreciseVehicleLocation()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vehicle.messages.ResponsePreciseVehicleLocation)
}
ResponsePreciseVehicleLocation::ResponsePreciseVehicleLocation(const ResponsePreciseVehicleLocation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_vehiclemessageheader()) {
    vehiclemessageheader_ = new ::com::vehicle::messages::VehicleMessageHeader(*from.vehiclemessageheader_);
  } else {
    vehiclemessageheader_ = nullptr;
  }
  if (from._internal_has_response_condition()) {
    response_condition_ = new ::com::vehicle::messages::ResponseCondition(*from.response_condition_);
  } else {
    response_condition_ = nullptr;
  }
  ::memcpy(&latitude_, &from.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&position_direction_) -
    reinterpret_cast<char*>(&latitude_)) + sizeof(position_direction_));
  // @@protoc_insertion_point(copy_constructor:com.vehicle.messages.ResponsePreciseVehicleLocation)
}

void ResponsePreciseVehicleLocation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ResponsePreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base);
  ::memset(&vehiclemessageheader_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&position_direction_) -
      reinterpret_cast<char*>(&vehiclemessageheader_)) + sizeof(position_direction_));
}

ResponsePreciseVehicleLocation::~ResponsePreciseVehicleLocation() {
  // @@protoc_insertion_point(destructor:com.vehicle.messages.ResponsePreciseVehicleLocation)
  SharedDtor();
}

void ResponsePreciseVehicleLocation::SharedDtor() {
  if (this != internal_default_instance()) delete vehiclemessageheader_;
  if (this != internal_default_instance()) delete response_condition_;
}

void ResponsePreciseVehicleLocation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResponsePreciseVehicleLocation& ResponsePreciseVehicleLocation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResponsePreciseVehicleLocation_V2C_2fVehiclePrecisionLocation_2eproto.base);
  return *internal_default_instance();
}


void ResponsePreciseVehicleLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && vehiclemessageheader_ != nullptr) {
    delete vehiclemessageheader_;
  }
  vehiclemessageheader_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && response_condition_ != nullptr) {
    delete response_condition_;
  }
  response_condition_ = nullptr;
  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&position_direction_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(position_direction_));
  _internal_metadata_.Clear();
}

const char* ResponsePreciseVehicleLocation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_vehiclemessageheader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .com.vehicle.messages.ResponseCondition response_condition = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_response_condition(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double latitude = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double longitude = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 estimated_position_error = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          estimated_position_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double position_altitude = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          position_altitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_gps_fix_typeenum(static_cast<::com::vehicle::messages::gpsFixEnum>(val));
        } else goto handle_unusual;
        continue;
      // bool is_gps_fix_available = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          is_gps_fix_available_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 estimated_altitude_error = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          estimated_altitude_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double position_direction = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          position_direction_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResponsePreciseVehicleLocation::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  if (this->has_vehiclemessageheader()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, _Internal::vehiclemessageheader(this), target, stream);
  }

  // .com.vehicle.messages.ResponseCondition response_condition = 2;
  if (this->has_response_condition()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, _Internal::response_condition(this), target, stream);
  }

  // double latitude = 3;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_latitude(), target);
  }

  // double longitude = 4;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_longitude(), target);
  }

  // int32 estimated_position_error = 5;
  if (this->estimated_position_error() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_estimated_position_error(), target);
  }

  // double position_altitude = 6;
  if (!(this->position_altitude() <= 0 && this->position_altitude() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_position_altitude(), target);
  }

  // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
  if (this->gps_fix_typeenum() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      7, this->_internal_gps_fix_typeenum(), target);
  }

  // bool is_gps_fix_available = 8;
  if (this->is_gps_fix_available() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(8, this->_internal_is_gps_fix_available(), target);
  }

  // int32 estimated_altitude_error = 9;
  if (this->estimated_altitude_error() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(9, this->_internal_estimated_altitude_error(), target);
  }

  // double position_direction = 10;
  if (!(this->position_direction() <= 0 && this->position_direction() >= 0)) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_position_direction(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.vehicle.messages.ResponsePreciseVehicleLocation)
  return target;
}

size_t ResponsePreciseVehicleLocation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  if (this->has_vehiclemessageheader()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *vehiclemessageheader_);
  }

  // .com.vehicle.messages.ResponseCondition response_condition = 2;
  if (this->has_response_condition()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *response_condition_);
  }

  // double latitude = 3;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    total_size += 1 + 8;
  }

  // double longitude = 4;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    total_size += 1 + 8;
  }

  // double position_altitude = 6;
  if (!(this->position_altitude() <= 0 && this->position_altitude() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 estimated_position_error = 5;
  if (this->estimated_position_error() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_estimated_position_error());
  }

  // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
  if (this->gps_fix_typeenum() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_gps_fix_typeenum());
  }

  // bool is_gps_fix_available = 8;
  if (this->is_gps_fix_available() != 0) {
    total_size += 1 + 1;
  }

  // int32 estimated_altitude_error = 9;
  if (this->estimated_altitude_error() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_estimated_altitude_error());
  }

  // double position_direction = 10;
  if (!(this->position_direction() <= 0 && this->position_direction() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponsePreciseVehicleLocation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponsePreciseVehicleLocation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResponsePreciseVehicleLocation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vehicle.messages.ResponsePreciseVehicleLocation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vehicle.messages.ResponsePreciseVehicleLocation)
    MergeFrom(*source);
  }
}

void ResponsePreciseVehicleLocation::MergeFrom(const ResponsePreciseVehicleLocation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_vehiclemessageheader()) {
    _internal_mutable_vehiclemessageheader()->::com::vehicle::messages::VehicleMessageHeader::MergeFrom(from._internal_vehiclemessageheader());
  }
  if (from.has_response_condition()) {
    _internal_mutable_response_condition()->::com::vehicle::messages::ResponseCondition::MergeFrom(from._internal_response_condition());
  }
  if (!(from.latitude() <= 0 && from.latitude() >= 0)) {
    _internal_set_latitude(from._internal_latitude());
  }
  if (!(from.longitude() <= 0 && from.longitude() >= 0)) {
    _internal_set_longitude(from._internal_longitude());
  }
  if (!(from.position_altitude() <= 0 && from.position_altitude() >= 0)) {
    _internal_set_position_altitude(from._internal_position_altitude());
  }
  if (from.estimated_position_error() != 0) {
    _internal_set_estimated_position_error(from._internal_estimated_position_error());
  }
  if (from.gps_fix_typeenum() != 0) {
    _internal_set_gps_fix_typeenum(from._internal_gps_fix_typeenum());
  }
  if (from.is_gps_fix_available() != 0) {
    _internal_set_is_gps_fix_available(from._internal_is_gps_fix_available());
  }
  if (from.estimated_altitude_error() != 0) {
    _internal_set_estimated_altitude_error(from._internal_estimated_altitude_error());
  }
  if (!(from.position_direction() <= 0 && from.position_direction() >= 0)) {
    _internal_set_position_direction(from._internal_position_direction());
  }
}

void ResponsePreciseVehicleLocation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponsePreciseVehicleLocation::CopyFrom(const ResponsePreciseVehicleLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vehicle.messages.ResponsePreciseVehicleLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponsePreciseVehicleLocation::IsInitialized() const {
  return true;
}

void ResponsePreciseVehicleLocation::InternalSwap(ResponsePreciseVehicleLocation* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(vehiclemessageheader_, other->vehiclemessageheader_);
  swap(response_condition_, other->response_condition_);
  swap(latitude_, other->latitude_);
  swap(longitude_, other->longitude_);
  swap(position_altitude_, other->position_altitude_);
  swap(estimated_position_error_, other->estimated_position_error_);
  swap(gps_fix_typeenum_, other->gps_fix_typeenum_);
  swap(is_gps_fix_available_, other->is_gps_fix_available_);
  swap(estimated_altitude_error_, other->estimated_altitude_error_);
  swap(position_direction_, other->position_direction_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResponsePreciseVehicleLocation::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ResponseCondition::InitAsDefaultInstance() {
}
class ResponseCondition::_Internal {
 public:
};

ResponseCondition::ResponseCondition()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vehicle.messages.ResponseCondition)
}
ResponseCondition::ResponseCondition(const ResponseCondition& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  reason_code_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_reason_code().empty()) {
    reason_code_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.reason_code_);
  }
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:com.vehicle.messages.ResponseCondition)
}

void ResponseCondition::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto.base);
  reason_code_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  result_ = 0;
}

ResponseCondition::~ResponseCondition() {
  // @@protoc_insertion_point(destructor:com.vehicle.messages.ResponseCondition)
  SharedDtor();
}

void ResponseCondition::SharedDtor() {
  reason_code_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ResponseCondition::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResponseCondition& ResponseCondition::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResponseCondition_V2C_2fVehiclePrecisionLocation_2eproto.base);
  return *internal_default_instance();
}


void ResponseCondition::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vehicle.messages.ResponseCondition)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reason_code_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  result_ = 0;
  _internal_metadata_.Clear();
}

const char* ResponseCondition::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .com.vehicle.messages.ResponseCondition.resultsEnum result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::com::vehicle::messages::ResponseCondition_resultsEnum>(val));
        } else goto handle_unusual;
        continue;
      // string reason_code = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_reason_code(), ptr, ctx, "com.vehicle.messages.ResponseCondition.reason_code");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResponseCondition::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vehicle.messages.ResponseCondition)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.vehicle.messages.ResponseCondition.resultsEnum result = 1;
  if (this->result() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result(), target);
  }

  // string reason_code = 2;
  if (this->reason_code().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason_code().data(), static_cast<int>(this->_internal_reason_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.vehicle.messages.ResponseCondition.reason_code");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_reason_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.vehicle.messages.ResponseCondition)
  return target;
}

size_t ResponseCondition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vehicle.messages.ResponseCondition)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reason_code = 2;
  if (this->reason_code().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason_code());
  }

  // .com.vehicle.messages.ResponseCondition.resultsEnum result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_result());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponseCondition::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vehicle.messages.ResponseCondition)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponseCondition* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResponseCondition>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vehicle.messages.ResponseCondition)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vehicle.messages.ResponseCondition)
    MergeFrom(*source);
  }
}

void ResponseCondition::MergeFrom(const ResponseCondition& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vehicle.messages.ResponseCondition)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.reason_code().size() > 0) {

    reason_code_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.reason_code_);
  }
  if (from.result() != 0) {
    _internal_set_result(from._internal_result());
  }
}

void ResponseCondition::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vehicle.messages.ResponseCondition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponseCondition::CopyFrom(const ResponseCondition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vehicle.messages.ResponseCondition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponseCondition::IsInitialized() const {
  return true;
}

void ResponseCondition::InternalSwap(ResponseCondition* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  reason_code_.Swap(&other->reason_code_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(result_, other->result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResponseCondition::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace vehicle
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::vehicle::messages::PublishPreciseVehicleLocation* Arena::CreateMaybeMessage< ::com::vehicle::messages::PublishPreciseVehicleLocation >(Arena* arena) {
  return Arena::CreateInternal< ::com::vehicle::messages::PublishPreciseVehicleLocation >(arena);
}
template<> PROTOBUF_NOINLINE ::com::vehicle::messages::RequestPreciseVehicleLocation* Arena::CreateMaybeMessage< ::com::vehicle::messages::RequestPreciseVehicleLocation >(Arena* arena) {
  return Arena::CreateInternal< ::com::vehicle::messages::RequestPreciseVehicleLocation >(arena);
}
template<> PROTOBUF_NOINLINE ::com::vehicle::messages::ResponsePreciseVehicleLocation* Arena::CreateMaybeMessage< ::com::vehicle::messages::ResponsePreciseVehicleLocation >(Arena* arena) {
  return Arena::CreateInternal< ::com::vehicle::messages::ResponsePreciseVehicleLocation >(arena);
}
template<> PROTOBUF_NOINLINE ::com::vehicle::messages::ResponseCondition* Arena::CreateMaybeMessage< ::com::vehicle::messages::ResponseCondition >(Arena* arena) {
  return Arena::CreateInternal< ::com::vehicle::messages::ResponseCondition >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
