// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: V2C/VehiclePrecisionLocation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_V2C_2fVehiclePrecisionLocation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_V2C_2fVehiclePrecisionLocation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "V2C/VehicleMessageHeader.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_V2C_2fVehiclePrecisionLocation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_V2C_2fVehiclePrecisionLocation_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto;
namespace com {
namespace vehicle {
namespace messages {
class PublishPreciseVehicleLocation;
class PublishPreciseVehicleLocationDefaultTypeInternal;
extern PublishPreciseVehicleLocationDefaultTypeInternal _PublishPreciseVehicleLocation_default_instance_;
class RequestPreciseVehicleLocation;
class RequestPreciseVehicleLocationDefaultTypeInternal;
extern RequestPreciseVehicleLocationDefaultTypeInternal _RequestPreciseVehicleLocation_default_instance_;
class ResponseCondition;
class ResponseConditionDefaultTypeInternal;
extern ResponseConditionDefaultTypeInternal _ResponseCondition_default_instance_;
class ResponsePreciseVehicleLocation;
class ResponsePreciseVehicleLocationDefaultTypeInternal;
extern ResponsePreciseVehicleLocationDefaultTypeInternal _ResponsePreciseVehicleLocation_default_instance_;
}  // namespace messages
}  // namespace vehicle
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::vehicle::messages::PublishPreciseVehicleLocation* Arena::CreateMaybeMessage<::com::vehicle::messages::PublishPreciseVehicleLocation>(Arena*);
template<> ::com::vehicle::messages::RequestPreciseVehicleLocation* Arena::CreateMaybeMessage<::com::vehicle::messages::RequestPreciseVehicleLocation>(Arena*);
template<> ::com::vehicle::messages::ResponseCondition* Arena::CreateMaybeMessage<::com::vehicle::messages::ResponseCondition>(Arena*);
template<> ::com::vehicle::messages::ResponsePreciseVehicleLocation* Arena::CreateMaybeMessage<::com::vehicle::messages::ResponsePreciseVehicleLocation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace vehicle {
namespace messages {

enum ResponseCondition_resultsEnum : int {
  ResponseCondition_resultsEnum_SUCCESS = 0,
  ResponseCondition_resultsEnum_FAILED_SYSTEM_ERROR = 1,
  ResponseCondition_resultsEnum_FAILED_LOCATION_UNAVAILABLE = 2,
  ResponseCondition_resultsEnum_ResponseCondition_resultsEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ResponseCondition_resultsEnum_ResponseCondition_resultsEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ResponseCondition_resultsEnum_IsValid(int value);
constexpr ResponseCondition_resultsEnum ResponseCondition_resultsEnum_resultsEnum_MIN = ResponseCondition_resultsEnum_SUCCESS;
constexpr ResponseCondition_resultsEnum ResponseCondition_resultsEnum_resultsEnum_MAX = ResponseCondition_resultsEnum_FAILED_LOCATION_UNAVAILABLE;
constexpr int ResponseCondition_resultsEnum_resultsEnum_ARRAYSIZE = ResponseCondition_resultsEnum_resultsEnum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResponseCondition_resultsEnum_descriptor();
template<typename T>
inline const std::string& ResponseCondition_resultsEnum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResponseCondition_resultsEnum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResponseCondition_resultsEnum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResponseCondition_resultsEnum_descriptor(), enum_t_value);
}
inline bool ResponseCondition_resultsEnum_Parse(
    const std::string& name, ResponseCondition_resultsEnum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResponseCondition_resultsEnum>(
    ResponseCondition_resultsEnum_descriptor(), name, value);
}
enum gpsFixEnum : int {
  ID_FIX_NO_POS = 0,
  ID_FIX_3D = 1,
  ID_FIX_2D = 2,
  ID_FIX_ESTIMATED = 3,
  gpsFixEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  gpsFixEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool gpsFixEnum_IsValid(int value);
constexpr gpsFixEnum gpsFixEnum_MIN = ID_FIX_NO_POS;
constexpr gpsFixEnum gpsFixEnum_MAX = ID_FIX_ESTIMATED;
constexpr int gpsFixEnum_ARRAYSIZE = gpsFixEnum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* gpsFixEnum_descriptor();
template<typename T>
inline const std::string& gpsFixEnum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, gpsFixEnum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function gpsFixEnum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    gpsFixEnum_descriptor(), enum_t_value);
}
inline bool gpsFixEnum_Parse(
    const std::string& name, gpsFixEnum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<gpsFixEnum>(
    gpsFixEnum_descriptor(), name, value);
}
// ===================================================================

class PublishPreciseVehicleLocation :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.vehicle.messages.PublishPreciseVehicleLocation) */ {
 public:
  PublishPreciseVehicleLocation();
  virtual ~PublishPreciseVehicleLocation();

  PublishPreciseVehicleLocation(const PublishPreciseVehicleLocation& from);
  PublishPreciseVehicleLocation(PublishPreciseVehicleLocation&& from) noexcept
    : PublishPreciseVehicleLocation() {
    *this = ::std::move(from);
  }

  inline PublishPreciseVehicleLocation& operator=(const PublishPreciseVehicleLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublishPreciseVehicleLocation& operator=(PublishPreciseVehicleLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PublishPreciseVehicleLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PublishPreciseVehicleLocation* internal_default_instance() {
    return reinterpret_cast<const PublishPreciseVehicleLocation*>(
               &_PublishPreciseVehicleLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PublishPreciseVehicleLocation& a, PublishPreciseVehicleLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(PublishPreciseVehicleLocation* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PublishPreciseVehicleLocation* New() const final {
    return CreateMaybeMessage<PublishPreciseVehicleLocation>(nullptr);
  }

  PublishPreciseVehicleLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PublishPreciseVehicleLocation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PublishPreciseVehicleLocation& from);
  void MergeFrom(const PublishPreciseVehicleLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublishPreciseVehicleLocation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.vehicle.messages.PublishPreciseVehicleLocation";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto);
    return ::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleMessageHeaderFieldNumber = 1,
    kLatitudeFieldNumber = 3,
    kLongitudeFieldNumber = 4,
    kPositionAltitudeFieldNumber = 6,
    kEstimatedPositionErrorFieldNumber = 5,
    kGpsFixTypeEnumFieldNumber = 7,
    kIsGpsFixAvailableFieldNumber = 8,
    kEstimatedAltitudeErrorFieldNumber = 9,
    kPositionDirectionFieldNumber = 10,
  };
  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  bool has_vehiclemessageheader() const;
  private:
  bool _internal_has_vehiclemessageheader() const;
  public:
  void clear_vehiclemessageheader();
  const ::com::vehicle::messages::VehicleMessageHeader& vehiclemessageheader() const;
  ::com::vehicle::messages::VehicleMessageHeader* release_vehiclemessageheader();
  ::com::vehicle::messages::VehicleMessageHeader* mutable_vehiclemessageheader();
  void set_allocated_vehiclemessageheader(::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader);
  private:
  const ::com::vehicle::messages::VehicleMessageHeader& _internal_vehiclemessageheader() const;
  ::com::vehicle::messages::VehicleMessageHeader* _internal_mutable_vehiclemessageheader();
  public:

  // double latitude = 3;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double longitude = 4;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double position_altitude = 6;
  void clear_position_altitude();
  double position_altitude() const;
  void set_position_altitude(double value);
  private:
  double _internal_position_altitude() const;
  void _internal_set_position_altitude(double value);
  public:

  // int32 estimated_position_error = 5;
  void clear_estimated_position_error();
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_position_error() const;
  void set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_estimated_position_error() const;
  void _internal_set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
  void clear_gps_fix_typeenum();
  ::com::vehicle::messages::gpsFixEnum gps_fix_typeenum() const;
  void set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value);
  private:
  ::com::vehicle::messages::gpsFixEnum _internal_gps_fix_typeenum() const;
  void _internal_set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value);
  public:

  // bool is_gps_fix_available = 8;
  void clear_is_gps_fix_available();
  bool is_gps_fix_available() const;
  void set_is_gps_fix_available(bool value);
  private:
  bool _internal_is_gps_fix_available() const;
  void _internal_set_is_gps_fix_available(bool value);
  public:

  // int32 estimated_altitude_error = 9;
  void clear_estimated_altitude_error();
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_altitude_error() const;
  void set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_estimated_altitude_error() const;
  void _internal_set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // double position_direction = 10;
  void clear_position_direction();
  double position_direction() const;
  void set_position_direction(double value);
  private:
  double _internal_position_direction() const;
  void _internal_set_position_direction(double value);
  public:

  // @@protoc_insertion_point(class_scope:com.vehicle.messages.PublishPreciseVehicleLocation)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader_;
  double latitude_;
  double longitude_;
  double position_altitude_;
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_position_error_;
  int gps_fix_typeenum_;
  bool is_gps_fix_available_;
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_altitude_error_;
  double position_direction_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_V2C_2fVehiclePrecisionLocation_2eproto;
};
// -------------------------------------------------------------------

class RequestPreciseVehicleLocation :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.vehicle.messages.RequestPreciseVehicleLocation) */ {
 public:
  RequestPreciseVehicleLocation();
  virtual ~RequestPreciseVehicleLocation();

  RequestPreciseVehicleLocation(const RequestPreciseVehicleLocation& from);
  RequestPreciseVehicleLocation(RequestPreciseVehicleLocation&& from) noexcept
    : RequestPreciseVehicleLocation() {
    *this = ::std::move(from);
  }

  inline RequestPreciseVehicleLocation& operator=(const RequestPreciseVehicleLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestPreciseVehicleLocation& operator=(RequestPreciseVehicleLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RequestPreciseVehicleLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestPreciseVehicleLocation* internal_default_instance() {
    return reinterpret_cast<const RequestPreciseVehicleLocation*>(
               &_RequestPreciseVehicleLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RequestPreciseVehicleLocation& a, RequestPreciseVehicleLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestPreciseVehicleLocation* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RequestPreciseVehicleLocation* New() const final {
    return CreateMaybeMessage<RequestPreciseVehicleLocation>(nullptr);
  }

  RequestPreciseVehicleLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RequestPreciseVehicleLocation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RequestPreciseVehicleLocation& from);
  void MergeFrom(const RequestPreciseVehicleLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestPreciseVehicleLocation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.vehicle.messages.RequestPreciseVehicleLocation";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto);
    return ::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleMessageHeaderFieldNumber = 1,
  };
  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  bool has_vehiclemessageheader() const;
  private:
  bool _internal_has_vehiclemessageheader() const;
  public:
  void clear_vehiclemessageheader();
  const ::com::vehicle::messages::VehicleMessageHeader& vehiclemessageheader() const;
  ::com::vehicle::messages::VehicleMessageHeader* release_vehiclemessageheader();
  ::com::vehicle::messages::VehicleMessageHeader* mutable_vehiclemessageheader();
  void set_allocated_vehiclemessageheader(::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader);
  private:
  const ::com::vehicle::messages::VehicleMessageHeader& _internal_vehiclemessageheader() const;
  ::com::vehicle::messages::VehicleMessageHeader* _internal_mutable_vehiclemessageheader();
  public:

  // @@protoc_insertion_point(class_scope:com.vehicle.messages.RequestPreciseVehicleLocation)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_V2C_2fVehiclePrecisionLocation_2eproto;
};
// -------------------------------------------------------------------

class ResponsePreciseVehicleLocation :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.vehicle.messages.ResponsePreciseVehicleLocation) */ {
 public:
  ResponsePreciseVehicleLocation();
  virtual ~ResponsePreciseVehicleLocation();

  ResponsePreciseVehicleLocation(const ResponsePreciseVehicleLocation& from);
  ResponsePreciseVehicleLocation(ResponsePreciseVehicleLocation&& from) noexcept
    : ResponsePreciseVehicleLocation() {
    *this = ::std::move(from);
  }

  inline ResponsePreciseVehicleLocation& operator=(const ResponsePreciseVehicleLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponsePreciseVehicleLocation& operator=(ResponsePreciseVehicleLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResponsePreciseVehicleLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponsePreciseVehicleLocation* internal_default_instance() {
    return reinterpret_cast<const ResponsePreciseVehicleLocation*>(
               &_ResponsePreciseVehicleLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ResponsePreciseVehicleLocation& a, ResponsePreciseVehicleLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(ResponsePreciseVehicleLocation* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResponsePreciseVehicleLocation* New() const final {
    return CreateMaybeMessage<ResponsePreciseVehicleLocation>(nullptr);
  }

  ResponsePreciseVehicleLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResponsePreciseVehicleLocation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResponsePreciseVehicleLocation& from);
  void MergeFrom(const ResponsePreciseVehicleLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponsePreciseVehicleLocation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.vehicle.messages.ResponsePreciseVehicleLocation";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto);
    return ::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleMessageHeaderFieldNumber = 1,
    kResponseConditionFieldNumber = 2,
    kLatitudeFieldNumber = 3,
    kLongitudeFieldNumber = 4,
    kPositionAltitudeFieldNumber = 6,
    kEstimatedPositionErrorFieldNumber = 5,
    kGpsFixTypeEnumFieldNumber = 7,
    kIsGpsFixAvailableFieldNumber = 8,
    kEstimatedAltitudeErrorFieldNumber = 9,
    kPositionDirectionFieldNumber = 10,
  };
  // .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
  bool has_vehiclemessageheader() const;
  private:
  bool _internal_has_vehiclemessageheader() const;
  public:
  void clear_vehiclemessageheader();
  const ::com::vehicle::messages::VehicleMessageHeader& vehiclemessageheader() const;
  ::com::vehicle::messages::VehicleMessageHeader* release_vehiclemessageheader();
  ::com::vehicle::messages::VehicleMessageHeader* mutable_vehiclemessageheader();
  void set_allocated_vehiclemessageheader(::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader);
  private:
  const ::com::vehicle::messages::VehicleMessageHeader& _internal_vehiclemessageheader() const;
  ::com::vehicle::messages::VehicleMessageHeader* _internal_mutable_vehiclemessageheader();
  public:

  // .com.vehicle.messages.ResponseCondition response_condition = 2;
  bool has_response_condition() const;
  private:
  bool _internal_has_response_condition() const;
  public:
  void clear_response_condition();
  const ::com::vehicle::messages::ResponseCondition& response_condition() const;
  ::com::vehicle::messages::ResponseCondition* release_response_condition();
  ::com::vehicle::messages::ResponseCondition* mutable_response_condition();
  void set_allocated_response_condition(::com::vehicle::messages::ResponseCondition* response_condition);
  private:
  const ::com::vehicle::messages::ResponseCondition& _internal_response_condition() const;
  ::com::vehicle::messages::ResponseCondition* _internal_mutable_response_condition();
  public:

  // double latitude = 3;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double longitude = 4;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // double position_altitude = 6;
  void clear_position_altitude();
  double position_altitude() const;
  void set_position_altitude(double value);
  private:
  double _internal_position_altitude() const;
  void _internal_set_position_altitude(double value);
  public:

  // int32 estimated_position_error = 5;
  void clear_estimated_position_error();
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_position_error() const;
  void set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_estimated_position_error() const;
  void _internal_set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
  void clear_gps_fix_typeenum();
  ::com::vehicle::messages::gpsFixEnum gps_fix_typeenum() const;
  void set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value);
  private:
  ::com::vehicle::messages::gpsFixEnum _internal_gps_fix_typeenum() const;
  void _internal_set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value);
  public:

  // bool is_gps_fix_available = 8;
  void clear_is_gps_fix_available();
  bool is_gps_fix_available() const;
  void set_is_gps_fix_available(bool value);
  private:
  bool _internal_is_gps_fix_available() const;
  void _internal_set_is_gps_fix_available(bool value);
  public:

  // int32 estimated_altitude_error = 9;
  void clear_estimated_altitude_error();
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_altitude_error() const;
  void set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_estimated_altitude_error() const;
  void _internal_set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // double position_direction = 10;
  void clear_position_direction();
  double position_direction() const;
  void set_position_direction(double value);
  private:
  double _internal_position_direction() const;
  void _internal_set_position_direction(double value);
  public:

  // @@protoc_insertion_point(class_scope:com.vehicle.messages.ResponsePreciseVehicleLocation)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader_;
  ::com::vehicle::messages::ResponseCondition* response_condition_;
  double latitude_;
  double longitude_;
  double position_altitude_;
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_position_error_;
  int gps_fix_typeenum_;
  bool is_gps_fix_available_;
  ::PROTOBUF_NAMESPACE_ID::int32 estimated_altitude_error_;
  double position_direction_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_V2C_2fVehiclePrecisionLocation_2eproto;
};
// -------------------------------------------------------------------

class ResponseCondition :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.vehicle.messages.ResponseCondition) */ {
 public:
  ResponseCondition();
  virtual ~ResponseCondition();

  ResponseCondition(const ResponseCondition& from);
  ResponseCondition(ResponseCondition&& from) noexcept
    : ResponseCondition() {
    *this = ::std::move(from);
  }

  inline ResponseCondition& operator=(const ResponseCondition& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponseCondition& operator=(ResponseCondition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResponseCondition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponseCondition* internal_default_instance() {
    return reinterpret_cast<const ResponseCondition*>(
               &_ResponseCondition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ResponseCondition& a, ResponseCondition& b) {
    a.Swap(&b);
  }
  inline void Swap(ResponseCondition* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResponseCondition* New() const final {
    return CreateMaybeMessage<ResponseCondition>(nullptr);
  }

  ResponseCondition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResponseCondition>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResponseCondition& from);
  void MergeFrom(const ResponseCondition& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponseCondition* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.vehicle.messages.ResponseCondition";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto);
    return ::descriptor_table_V2C_2fVehiclePrecisionLocation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ResponseCondition_resultsEnum resultsEnum;
  static constexpr resultsEnum SUCCESS =
    ResponseCondition_resultsEnum_SUCCESS;
  static constexpr resultsEnum FAILED_SYSTEM_ERROR =
    ResponseCondition_resultsEnum_FAILED_SYSTEM_ERROR;
  static constexpr resultsEnum FAILED_LOCATION_UNAVAILABLE =
    ResponseCondition_resultsEnum_FAILED_LOCATION_UNAVAILABLE;
  static inline bool resultsEnum_IsValid(int value) {
    return ResponseCondition_resultsEnum_IsValid(value);
  }
  static constexpr resultsEnum resultsEnum_MIN =
    ResponseCondition_resultsEnum_resultsEnum_MIN;
  static constexpr resultsEnum resultsEnum_MAX =
    ResponseCondition_resultsEnum_resultsEnum_MAX;
  static constexpr int resultsEnum_ARRAYSIZE =
    ResponseCondition_resultsEnum_resultsEnum_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  resultsEnum_descriptor() {
    return ResponseCondition_resultsEnum_descriptor();
  }
  template<typename T>
  static inline const std::string& resultsEnum_Name(T enum_t_value) {
    static_assert(::std::is_same<T, resultsEnum>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function resultsEnum_Name.");
    return ResponseCondition_resultsEnum_Name(enum_t_value);
  }
  static inline bool resultsEnum_Parse(const std::string& name,
      resultsEnum* value) {
    return ResponseCondition_resultsEnum_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kReasonCodeFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // string reason_code = 2;
  void clear_reason_code();
  const std::string& reason_code() const;
  void set_reason_code(const std::string& value);
  void set_reason_code(std::string&& value);
  void set_reason_code(const char* value);
  void set_reason_code(const char* value, size_t size);
  std::string* mutable_reason_code();
  std::string* release_reason_code();
  void set_allocated_reason_code(std::string* reason_code);
  private:
  const std::string& _internal_reason_code() const;
  void _internal_set_reason_code(const std::string& value);
  std::string* _internal_mutable_reason_code();
  public:

  // .com.vehicle.messages.ResponseCondition.resultsEnum result = 1;
  void clear_result();
  ::com::vehicle::messages::ResponseCondition_resultsEnum result() const;
  void set_result(::com::vehicle::messages::ResponseCondition_resultsEnum value);
  private:
  ::com::vehicle::messages::ResponseCondition_resultsEnum _internal_result() const;
  void _internal_set_result(::com::vehicle::messages::ResponseCondition_resultsEnum value);
  public:

  // @@protoc_insertion_point(class_scope:com.vehicle.messages.ResponseCondition)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_code_;
  int result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_V2C_2fVehiclePrecisionLocation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PublishPreciseVehicleLocation

// .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
inline bool PublishPreciseVehicleLocation::_internal_has_vehiclemessageheader() const {
  return this != internal_default_instance() && vehiclemessageheader_ != nullptr;
}
inline bool PublishPreciseVehicleLocation::has_vehiclemessageheader() const {
  return _internal_has_vehiclemessageheader();
}
inline const ::com::vehicle::messages::VehicleMessageHeader& PublishPreciseVehicleLocation::_internal_vehiclemessageheader() const {
  const ::com::vehicle::messages::VehicleMessageHeader* p = vehiclemessageheader_;
  return p != nullptr ? *p : *reinterpret_cast<const ::com::vehicle::messages::VehicleMessageHeader*>(
      &::com::vehicle::messages::_VehicleMessageHeader_default_instance_);
}
inline const ::com::vehicle::messages::VehicleMessageHeader& PublishPreciseVehicleLocation::vehiclemessageheader() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.vehicleMessageHeader)
  return _internal_vehiclemessageheader();
}
inline ::com::vehicle::messages::VehicleMessageHeader* PublishPreciseVehicleLocation::release_vehiclemessageheader() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.PublishPreciseVehicleLocation.vehicleMessageHeader)
  
  ::com::vehicle::messages::VehicleMessageHeader* temp = vehiclemessageheader_;
  vehiclemessageheader_ = nullptr;
  return temp;
}
inline ::com::vehicle::messages::VehicleMessageHeader* PublishPreciseVehicleLocation::_internal_mutable_vehiclemessageheader() {
  
  if (vehiclemessageheader_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::vehicle::messages::VehicleMessageHeader>(GetArenaNoVirtual());
    vehiclemessageheader_ = p;
  }
  return vehiclemessageheader_;
}
inline ::com::vehicle::messages::VehicleMessageHeader* PublishPreciseVehicleLocation::mutable_vehiclemessageheader() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.PublishPreciseVehicleLocation.vehicleMessageHeader)
  return _internal_mutable_vehiclemessageheader();
}
inline void PublishPreciseVehicleLocation::set_allocated_vehiclemessageheader(::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vehiclemessageheader_);
  }
  if (vehiclemessageheader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      vehiclemessageheader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vehiclemessageheader, submessage_arena);
    }
    
  } else {
    
  }
  vehiclemessageheader_ = vehiclemessageheader;
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.PublishPreciseVehicleLocation.vehicleMessageHeader)
}

// double latitude = 3;
inline void PublishPreciseVehicleLocation::clear_latitude() {
  latitude_ = 0;
}
inline double PublishPreciseVehicleLocation::_internal_latitude() const {
  return latitude_;
}
inline double PublishPreciseVehicleLocation::latitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.latitude)
  return _internal_latitude();
}
inline void PublishPreciseVehicleLocation::_internal_set_latitude(double value) {
  
  latitude_ = value;
}
inline void PublishPreciseVehicleLocation::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.latitude)
}

// double longitude = 4;
inline void PublishPreciseVehicleLocation::clear_longitude() {
  longitude_ = 0;
}
inline double PublishPreciseVehicleLocation::_internal_longitude() const {
  return longitude_;
}
inline double PublishPreciseVehicleLocation::longitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.longitude)
  return _internal_longitude();
}
inline void PublishPreciseVehicleLocation::_internal_set_longitude(double value) {
  
  longitude_ = value;
}
inline void PublishPreciseVehicleLocation::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.longitude)
}

// int32 estimated_position_error = 5;
inline void PublishPreciseVehicleLocation::clear_estimated_position_error() {
  estimated_position_error_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PublishPreciseVehicleLocation::_internal_estimated_position_error() const {
  return estimated_position_error_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PublishPreciseVehicleLocation::estimated_position_error() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.estimated_position_error)
  return _internal_estimated_position_error();
}
inline void PublishPreciseVehicleLocation::_internal_set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  estimated_position_error_ = value;
}
inline void PublishPreciseVehicleLocation::set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_estimated_position_error(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.estimated_position_error)
}

// double position_altitude = 6;
inline void PublishPreciseVehicleLocation::clear_position_altitude() {
  position_altitude_ = 0;
}
inline double PublishPreciseVehicleLocation::_internal_position_altitude() const {
  return position_altitude_;
}
inline double PublishPreciseVehicleLocation::position_altitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.position_altitude)
  return _internal_position_altitude();
}
inline void PublishPreciseVehicleLocation::_internal_set_position_altitude(double value) {
  
  position_altitude_ = value;
}
inline void PublishPreciseVehicleLocation::set_position_altitude(double value) {
  _internal_set_position_altitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.position_altitude)
}

// .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
inline void PublishPreciseVehicleLocation::clear_gps_fix_typeenum() {
  gps_fix_typeenum_ = 0;
}
inline ::com::vehicle::messages::gpsFixEnum PublishPreciseVehicleLocation::_internal_gps_fix_typeenum() const {
  return static_cast< ::com::vehicle::messages::gpsFixEnum >(gps_fix_typeenum_);
}
inline ::com::vehicle::messages::gpsFixEnum PublishPreciseVehicleLocation::gps_fix_typeenum() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.gps_fix_typeEnum)
  return _internal_gps_fix_typeenum();
}
inline void PublishPreciseVehicleLocation::_internal_set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value) {
  
  gps_fix_typeenum_ = value;
}
inline void PublishPreciseVehicleLocation::set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value) {
  _internal_set_gps_fix_typeenum(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.gps_fix_typeEnum)
}

// bool is_gps_fix_available = 8;
inline void PublishPreciseVehicleLocation::clear_is_gps_fix_available() {
  is_gps_fix_available_ = false;
}
inline bool PublishPreciseVehicleLocation::_internal_is_gps_fix_available() const {
  return is_gps_fix_available_;
}
inline bool PublishPreciseVehicleLocation::is_gps_fix_available() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.is_gps_fix_available)
  return _internal_is_gps_fix_available();
}
inline void PublishPreciseVehicleLocation::_internal_set_is_gps_fix_available(bool value) {
  
  is_gps_fix_available_ = value;
}
inline void PublishPreciseVehicleLocation::set_is_gps_fix_available(bool value) {
  _internal_set_is_gps_fix_available(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.is_gps_fix_available)
}

// int32 estimated_altitude_error = 9;
inline void PublishPreciseVehicleLocation::clear_estimated_altitude_error() {
  estimated_altitude_error_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PublishPreciseVehicleLocation::_internal_estimated_altitude_error() const {
  return estimated_altitude_error_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PublishPreciseVehicleLocation::estimated_altitude_error() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.estimated_altitude_error)
  return _internal_estimated_altitude_error();
}
inline void PublishPreciseVehicleLocation::_internal_set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  estimated_altitude_error_ = value;
}
inline void PublishPreciseVehicleLocation::set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_estimated_altitude_error(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.estimated_altitude_error)
}

// double position_direction = 10;
inline void PublishPreciseVehicleLocation::clear_position_direction() {
  position_direction_ = 0;
}
inline double PublishPreciseVehicleLocation::_internal_position_direction() const {
  return position_direction_;
}
inline double PublishPreciseVehicleLocation::position_direction() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.PublishPreciseVehicleLocation.position_direction)
  return _internal_position_direction();
}
inline void PublishPreciseVehicleLocation::_internal_set_position_direction(double value) {
  
  position_direction_ = value;
}
inline void PublishPreciseVehicleLocation::set_position_direction(double value) {
  _internal_set_position_direction(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.PublishPreciseVehicleLocation.position_direction)
}

// -------------------------------------------------------------------

// RequestPreciseVehicleLocation

// .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
inline bool RequestPreciseVehicleLocation::_internal_has_vehiclemessageheader() const {
  return this != internal_default_instance() && vehiclemessageheader_ != nullptr;
}
inline bool RequestPreciseVehicleLocation::has_vehiclemessageheader() const {
  return _internal_has_vehiclemessageheader();
}
inline const ::com::vehicle::messages::VehicleMessageHeader& RequestPreciseVehicleLocation::_internal_vehiclemessageheader() const {
  const ::com::vehicle::messages::VehicleMessageHeader* p = vehiclemessageheader_;
  return p != nullptr ? *p : *reinterpret_cast<const ::com::vehicle::messages::VehicleMessageHeader*>(
      &::com::vehicle::messages::_VehicleMessageHeader_default_instance_);
}
inline const ::com::vehicle::messages::VehicleMessageHeader& RequestPreciseVehicleLocation::vehiclemessageheader() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.RequestPreciseVehicleLocation.vehicleMessageHeader)
  return _internal_vehiclemessageheader();
}
inline ::com::vehicle::messages::VehicleMessageHeader* RequestPreciseVehicleLocation::release_vehiclemessageheader() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.RequestPreciseVehicleLocation.vehicleMessageHeader)
  
  ::com::vehicle::messages::VehicleMessageHeader* temp = vehiclemessageheader_;
  vehiclemessageheader_ = nullptr;
  return temp;
}
inline ::com::vehicle::messages::VehicleMessageHeader* RequestPreciseVehicleLocation::_internal_mutable_vehiclemessageheader() {
  
  if (vehiclemessageheader_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::vehicle::messages::VehicleMessageHeader>(GetArenaNoVirtual());
    vehiclemessageheader_ = p;
  }
  return vehiclemessageheader_;
}
inline ::com::vehicle::messages::VehicleMessageHeader* RequestPreciseVehicleLocation::mutable_vehiclemessageheader() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.RequestPreciseVehicleLocation.vehicleMessageHeader)
  return _internal_mutable_vehiclemessageheader();
}
inline void RequestPreciseVehicleLocation::set_allocated_vehiclemessageheader(::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vehiclemessageheader_);
  }
  if (vehiclemessageheader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      vehiclemessageheader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vehiclemessageheader, submessage_arena);
    }
    
  } else {
    
  }
  vehiclemessageheader_ = vehiclemessageheader;
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.RequestPreciseVehicleLocation.vehicleMessageHeader)
}

// -------------------------------------------------------------------

// ResponsePreciseVehicleLocation

// .com.vehicle.messages.VehicleMessageHeader vehicleMessageHeader = 1;
inline bool ResponsePreciseVehicleLocation::_internal_has_vehiclemessageheader() const {
  return this != internal_default_instance() && vehiclemessageheader_ != nullptr;
}
inline bool ResponsePreciseVehicleLocation::has_vehiclemessageheader() const {
  return _internal_has_vehiclemessageheader();
}
inline const ::com::vehicle::messages::VehicleMessageHeader& ResponsePreciseVehicleLocation::_internal_vehiclemessageheader() const {
  const ::com::vehicle::messages::VehicleMessageHeader* p = vehiclemessageheader_;
  return p != nullptr ? *p : *reinterpret_cast<const ::com::vehicle::messages::VehicleMessageHeader*>(
      &::com::vehicle::messages::_VehicleMessageHeader_default_instance_);
}
inline const ::com::vehicle::messages::VehicleMessageHeader& ResponsePreciseVehicleLocation::vehiclemessageheader() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.vehicleMessageHeader)
  return _internal_vehiclemessageheader();
}
inline ::com::vehicle::messages::VehicleMessageHeader* ResponsePreciseVehicleLocation::release_vehiclemessageheader() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.ResponsePreciseVehicleLocation.vehicleMessageHeader)
  
  ::com::vehicle::messages::VehicleMessageHeader* temp = vehiclemessageheader_;
  vehiclemessageheader_ = nullptr;
  return temp;
}
inline ::com::vehicle::messages::VehicleMessageHeader* ResponsePreciseVehicleLocation::_internal_mutable_vehiclemessageheader() {
  
  if (vehiclemessageheader_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::vehicle::messages::VehicleMessageHeader>(GetArenaNoVirtual());
    vehiclemessageheader_ = p;
  }
  return vehiclemessageheader_;
}
inline ::com::vehicle::messages::VehicleMessageHeader* ResponsePreciseVehicleLocation::mutable_vehiclemessageheader() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.ResponsePreciseVehicleLocation.vehicleMessageHeader)
  return _internal_mutable_vehiclemessageheader();
}
inline void ResponsePreciseVehicleLocation::set_allocated_vehiclemessageheader(::com::vehicle::messages::VehicleMessageHeader* vehiclemessageheader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vehiclemessageheader_);
  }
  if (vehiclemessageheader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      vehiclemessageheader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vehiclemessageheader, submessage_arena);
    }
    
  } else {
    
  }
  vehiclemessageheader_ = vehiclemessageheader;
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.ResponsePreciseVehicleLocation.vehicleMessageHeader)
}

// .com.vehicle.messages.ResponseCondition response_condition = 2;
inline bool ResponsePreciseVehicleLocation::_internal_has_response_condition() const {
  return this != internal_default_instance() && response_condition_ != nullptr;
}
inline bool ResponsePreciseVehicleLocation::has_response_condition() const {
  return _internal_has_response_condition();
}
inline void ResponsePreciseVehicleLocation::clear_response_condition() {
  if (GetArenaNoVirtual() == nullptr && response_condition_ != nullptr) {
    delete response_condition_;
  }
  response_condition_ = nullptr;
}
inline const ::com::vehicle::messages::ResponseCondition& ResponsePreciseVehicleLocation::_internal_response_condition() const {
  const ::com::vehicle::messages::ResponseCondition* p = response_condition_;
  return p != nullptr ? *p : *reinterpret_cast<const ::com::vehicle::messages::ResponseCondition*>(
      &::com::vehicle::messages::_ResponseCondition_default_instance_);
}
inline const ::com::vehicle::messages::ResponseCondition& ResponsePreciseVehicleLocation::response_condition() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.response_condition)
  return _internal_response_condition();
}
inline ::com::vehicle::messages::ResponseCondition* ResponsePreciseVehicleLocation::release_response_condition() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.ResponsePreciseVehicleLocation.response_condition)
  
  ::com::vehicle::messages::ResponseCondition* temp = response_condition_;
  response_condition_ = nullptr;
  return temp;
}
inline ::com::vehicle::messages::ResponseCondition* ResponsePreciseVehicleLocation::_internal_mutable_response_condition() {
  
  if (response_condition_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::vehicle::messages::ResponseCondition>(GetArenaNoVirtual());
    response_condition_ = p;
  }
  return response_condition_;
}
inline ::com::vehicle::messages::ResponseCondition* ResponsePreciseVehicleLocation::mutable_response_condition() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.ResponsePreciseVehicleLocation.response_condition)
  return _internal_mutable_response_condition();
}
inline void ResponsePreciseVehicleLocation::set_allocated_response_condition(::com::vehicle::messages::ResponseCondition* response_condition) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete response_condition_;
  }
  if (response_condition) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      response_condition = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, response_condition, submessage_arena);
    }
    
  } else {
    
  }
  response_condition_ = response_condition;
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.ResponsePreciseVehicleLocation.response_condition)
}

// double latitude = 3;
inline void ResponsePreciseVehicleLocation::clear_latitude() {
  latitude_ = 0;
}
inline double ResponsePreciseVehicleLocation::_internal_latitude() const {
  return latitude_;
}
inline double ResponsePreciseVehicleLocation::latitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.latitude)
  return _internal_latitude();
}
inline void ResponsePreciseVehicleLocation::_internal_set_latitude(double value) {
  
  latitude_ = value;
}
inline void ResponsePreciseVehicleLocation::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.latitude)
}

// double longitude = 4;
inline void ResponsePreciseVehicleLocation::clear_longitude() {
  longitude_ = 0;
}
inline double ResponsePreciseVehicleLocation::_internal_longitude() const {
  return longitude_;
}
inline double ResponsePreciseVehicleLocation::longitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.longitude)
  return _internal_longitude();
}
inline void ResponsePreciseVehicleLocation::_internal_set_longitude(double value) {
  
  longitude_ = value;
}
inline void ResponsePreciseVehicleLocation::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.longitude)
}

// int32 estimated_position_error = 5;
inline void ResponsePreciseVehicleLocation::clear_estimated_position_error() {
  estimated_position_error_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResponsePreciseVehicleLocation::_internal_estimated_position_error() const {
  return estimated_position_error_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResponsePreciseVehicleLocation::estimated_position_error() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.estimated_position_error)
  return _internal_estimated_position_error();
}
inline void ResponsePreciseVehicleLocation::_internal_set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  estimated_position_error_ = value;
}
inline void ResponsePreciseVehicleLocation::set_estimated_position_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_estimated_position_error(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.estimated_position_error)
}

// double position_altitude = 6;
inline void ResponsePreciseVehicleLocation::clear_position_altitude() {
  position_altitude_ = 0;
}
inline double ResponsePreciseVehicleLocation::_internal_position_altitude() const {
  return position_altitude_;
}
inline double ResponsePreciseVehicleLocation::position_altitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.position_altitude)
  return _internal_position_altitude();
}
inline void ResponsePreciseVehicleLocation::_internal_set_position_altitude(double value) {
  
  position_altitude_ = value;
}
inline void ResponsePreciseVehicleLocation::set_position_altitude(double value) {
  _internal_set_position_altitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.position_altitude)
}

// .com.vehicle.messages.gpsFixEnum gps_fix_typeEnum = 7;
inline void ResponsePreciseVehicleLocation::clear_gps_fix_typeenum() {
  gps_fix_typeenum_ = 0;
}
inline ::com::vehicle::messages::gpsFixEnum ResponsePreciseVehicleLocation::_internal_gps_fix_typeenum() const {
  return static_cast< ::com::vehicle::messages::gpsFixEnum >(gps_fix_typeenum_);
}
inline ::com::vehicle::messages::gpsFixEnum ResponsePreciseVehicleLocation::gps_fix_typeenum() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.gps_fix_typeEnum)
  return _internal_gps_fix_typeenum();
}
inline void ResponsePreciseVehicleLocation::_internal_set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value) {
  
  gps_fix_typeenum_ = value;
}
inline void ResponsePreciseVehicleLocation::set_gps_fix_typeenum(::com::vehicle::messages::gpsFixEnum value) {
  _internal_set_gps_fix_typeenum(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.gps_fix_typeEnum)
}

// bool is_gps_fix_available = 8;
inline void ResponsePreciseVehicleLocation::clear_is_gps_fix_available() {
  is_gps_fix_available_ = false;
}
inline bool ResponsePreciseVehicleLocation::_internal_is_gps_fix_available() const {
  return is_gps_fix_available_;
}
inline bool ResponsePreciseVehicleLocation::is_gps_fix_available() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.is_gps_fix_available)
  return _internal_is_gps_fix_available();
}
inline void ResponsePreciseVehicleLocation::_internal_set_is_gps_fix_available(bool value) {
  
  is_gps_fix_available_ = value;
}
inline void ResponsePreciseVehicleLocation::set_is_gps_fix_available(bool value) {
  _internal_set_is_gps_fix_available(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.is_gps_fix_available)
}

// int32 estimated_altitude_error = 9;
inline void ResponsePreciseVehicleLocation::clear_estimated_altitude_error() {
  estimated_altitude_error_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResponsePreciseVehicleLocation::_internal_estimated_altitude_error() const {
  return estimated_altitude_error_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResponsePreciseVehicleLocation::estimated_altitude_error() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.estimated_altitude_error)
  return _internal_estimated_altitude_error();
}
inline void ResponsePreciseVehicleLocation::_internal_set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  estimated_altitude_error_ = value;
}
inline void ResponsePreciseVehicleLocation::set_estimated_altitude_error(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_estimated_altitude_error(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.estimated_altitude_error)
}

// double position_direction = 10;
inline void ResponsePreciseVehicleLocation::clear_position_direction() {
  position_direction_ = 0;
}
inline double ResponsePreciseVehicleLocation::_internal_position_direction() const {
  return position_direction_;
}
inline double ResponsePreciseVehicleLocation::position_direction() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponsePreciseVehicleLocation.position_direction)
  return _internal_position_direction();
}
inline void ResponsePreciseVehicleLocation::_internal_set_position_direction(double value) {
  
  position_direction_ = value;
}
inline void ResponsePreciseVehicleLocation::set_position_direction(double value) {
  _internal_set_position_direction(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponsePreciseVehicleLocation.position_direction)
}

// -------------------------------------------------------------------

// ResponseCondition

// .com.vehicle.messages.ResponseCondition.resultsEnum result = 1;
inline void ResponseCondition::clear_result() {
  result_ = 0;
}
inline ::com::vehicle::messages::ResponseCondition_resultsEnum ResponseCondition::_internal_result() const {
  return static_cast< ::com::vehicle::messages::ResponseCondition_resultsEnum >(result_);
}
inline ::com::vehicle::messages::ResponseCondition_resultsEnum ResponseCondition::result() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponseCondition.result)
  return _internal_result();
}
inline void ResponseCondition::_internal_set_result(::com::vehicle::messages::ResponseCondition_resultsEnum value) {
  
  result_ = value;
}
inline void ResponseCondition::set_result(::com::vehicle::messages::ResponseCondition_resultsEnum value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponseCondition.result)
}

// string reason_code = 2;
inline void ResponseCondition::clear_reason_code() {
  reason_code_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResponseCondition::reason_code() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.ResponseCondition.reason_code)
  return _internal_reason_code();
}
inline void ResponseCondition::set_reason_code(const std::string& value) {
  _internal_set_reason_code(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.ResponseCondition.reason_code)
}
inline std::string* ResponseCondition::mutable_reason_code() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.ResponseCondition.reason_code)
  return _internal_mutable_reason_code();
}
inline const std::string& ResponseCondition::_internal_reason_code() const {
  return reason_code_.GetNoArena();
}
inline void ResponseCondition::_internal_set_reason_code(const std::string& value) {
  
  reason_code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ResponseCondition::set_reason_code(std::string&& value) {
  
  reason_code_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vehicle.messages.ResponseCondition.reason_code)
}
inline void ResponseCondition::set_reason_code(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  reason_code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vehicle.messages.ResponseCondition.reason_code)
}
inline void ResponseCondition::set_reason_code(const char* value, size_t size) {
  
  reason_code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vehicle.messages.ResponseCondition.reason_code)
}
inline std::string* ResponseCondition::_internal_mutable_reason_code() {
  
  return reason_code_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResponseCondition::release_reason_code() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.ResponseCondition.reason_code)
  
  return reason_code_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseCondition::set_allocated_reason_code(std::string* reason_code) {
  if (reason_code != nullptr) {
    
  } else {
    
  }
  reason_code_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reason_code);
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.ResponseCondition.reason_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace vehicle
}  // namespace com

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::com::vehicle::messages::ResponseCondition_resultsEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::vehicle::messages::ResponseCondition_resultsEnum>() {
  return ::com::vehicle::messages::ResponseCondition_resultsEnum_descriptor();
}
template <> struct is_proto_enum< ::com::vehicle::messages::gpsFixEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::vehicle::messages::gpsFixEnum>() {
  return ::com::vehicle::messages::gpsFixEnum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_V2C_2fVehiclePrecisionLocation_2eproto
