// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: V2C/VehicleMessageHeader.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_V2C_2fVehicleMessageHeader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_V2C_2fVehicleMessageHeader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_V2C_2fVehicleMessageHeader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_V2C_2fVehicleMessageHeader_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_V2C_2fVehicleMessageHeader_2eproto;
namespace com {
namespace vehicle {
namespace messages {
class VehicleMessageHeader;
class VehicleMessageHeaderDefaultTypeInternal;
extern VehicleMessageHeaderDefaultTypeInternal _VehicleMessageHeader_default_instance_;
class lat_long;
class lat_longDefaultTypeInternal;
extern lat_longDefaultTypeInternal _lat_long_default_instance_;
}  // namespace messages
}  // namespace vehicle
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::vehicle::messages::VehicleMessageHeader* Arena::CreateMaybeMessage<::com::vehicle::messages::VehicleMessageHeader>(Arena*);
template<> ::com::vehicle::messages::lat_long* Arena::CreateMaybeMessage<::com::vehicle::messages::lat_long>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace vehicle {
namespace messages {

// ===================================================================

class VehicleMessageHeader :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.vehicle.messages.VehicleMessageHeader) */ {
 public:
  VehicleMessageHeader();
  virtual ~VehicleMessageHeader();

  VehicleMessageHeader(const VehicleMessageHeader& from);
  VehicleMessageHeader(VehicleMessageHeader&& from) noexcept
    : VehicleMessageHeader() {
    *this = ::std::move(from);
  }

  inline VehicleMessageHeader& operator=(const VehicleMessageHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline VehicleMessageHeader& operator=(VehicleMessageHeader&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VehicleMessageHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VehicleMessageHeader* internal_default_instance() {
    return reinterpret_cast<const VehicleMessageHeader*>(
               &_VehicleMessageHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VehicleMessageHeader& a, VehicleMessageHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(VehicleMessageHeader* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VehicleMessageHeader* New() const final {
    return CreateMaybeMessage<VehicleMessageHeader>(nullptr);
  }

  VehicleMessageHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VehicleMessageHeader>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VehicleMessageHeader& from);
  void MergeFrom(const VehicleMessageHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VehicleMessageHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.vehicle.messages.VehicleMessageHeader";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_V2C_2fVehicleMessageHeader_2eproto);
    return ::descriptor_table_V2C_2fVehicleMessageHeader_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleIdFieldNumber = 3,
    kLocationFieldNumber = 6,
    kMessageIdFieldNumber = 1,
    kCorrelationIdFieldNumber = 2,
    kMessageTimestampFieldNumber = 4,
    kProtocolVersionFieldNumber = 5,
  };
  // string vehicle_id = 3;
  void clear_vehicle_id();
  const std::string& vehicle_id() const;
  void set_vehicle_id(const std::string& value);
  void set_vehicle_id(std::string&& value);
  void set_vehicle_id(const char* value);
  void set_vehicle_id(const char* value, size_t size);
  std::string* mutable_vehicle_id();
  std::string* release_vehicle_id();
  void set_allocated_vehicle_id(std::string* vehicle_id);
  private:
  const std::string& _internal_vehicle_id() const;
  void _internal_set_vehicle_id(const std::string& value);
  std::string* _internal_mutable_vehicle_id();
  public:

  // .com.vehicle.messages.lat_long location = 6;
  bool has_location() const;
  private:
  bool _internal_has_location() const;
  public:
  void clear_location();
  const ::com::vehicle::messages::lat_long& location() const;
  ::com::vehicle::messages::lat_long* release_location();
  ::com::vehicle::messages::lat_long* mutable_location();
  void set_allocated_location(::com::vehicle::messages::lat_long* location);
  private:
  const ::com::vehicle::messages::lat_long& _internal_location() const;
  ::com::vehicle::messages::lat_long* _internal_mutable_location();
  public:

  // int32 message_id = 1;
  void clear_message_id();
  ::PROTOBUF_NAMESPACE_ID::int32 message_id() const;
  void set_message_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_message_id() const;
  void _internal_set_message_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 correlation_id = 2;
  void clear_correlation_id();
  ::PROTOBUF_NAMESPACE_ID::int32 correlation_id() const;
  void set_correlation_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_correlation_id() const;
  void _internal_set_correlation_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 message_timestamp = 4;
  void clear_message_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 message_timestamp() const;
  void set_message_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_message_timestamp() const;
  void _internal_set_message_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // double protocol_version = 5;
  void clear_protocol_version();
  double protocol_version() const;
  void set_protocol_version(double value);
  private:
  double _internal_protocol_version() const;
  void _internal_set_protocol_version(double value);
  public:

  // @@protoc_insertion_point(class_scope:com.vehicle.messages.VehicleMessageHeader)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vehicle_id_;
  ::com::vehicle::messages::lat_long* location_;
  ::PROTOBUF_NAMESPACE_ID::int32 message_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 correlation_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 message_timestamp_;
  double protocol_version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_V2C_2fVehicleMessageHeader_2eproto;
};
// -------------------------------------------------------------------

class lat_long :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.vehicle.messages.lat_long) */ {
 public:
  lat_long();
  virtual ~lat_long();

  lat_long(const lat_long& from);
  lat_long(lat_long&& from) noexcept
    : lat_long() {
    *this = ::std::move(from);
  }

  inline lat_long& operator=(const lat_long& from) {
    CopyFrom(from);
    return *this;
  }
  inline lat_long& operator=(lat_long&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const lat_long& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const lat_long* internal_default_instance() {
    return reinterpret_cast<const lat_long*>(
               &_lat_long_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(lat_long& a, lat_long& b) {
    a.Swap(&b);
  }
  inline void Swap(lat_long* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline lat_long* New() const final {
    return CreateMaybeMessage<lat_long>(nullptr);
  }

  lat_long* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<lat_long>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const lat_long& from);
  void MergeFrom(const lat_long& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(lat_long* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.vehicle.messages.lat_long";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_V2C_2fVehicleMessageHeader_2eproto);
    return ::descriptor_table_V2C_2fVehicleMessageHeader_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
  };
  // double latitude = 1;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double longitude = 2;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // @@protoc_insertion_point(class_scope:com.vehicle.messages.lat_long)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double latitude_;
  double longitude_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_V2C_2fVehicleMessageHeader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VehicleMessageHeader

// int32 message_id = 1;
inline void VehicleMessageHeader::clear_message_id() {
  message_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VehicleMessageHeader::_internal_message_id() const {
  return message_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VehicleMessageHeader::message_id() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.VehicleMessageHeader.message_id)
  return _internal_message_id();
}
inline void VehicleMessageHeader::_internal_set_message_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  message_id_ = value;
}
inline void VehicleMessageHeader::set_message_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_message_id(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.VehicleMessageHeader.message_id)
}

// int32 correlation_id = 2;
inline void VehicleMessageHeader::clear_correlation_id() {
  correlation_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VehicleMessageHeader::_internal_correlation_id() const {
  return correlation_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VehicleMessageHeader::correlation_id() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.VehicleMessageHeader.correlation_id)
  return _internal_correlation_id();
}
inline void VehicleMessageHeader::_internal_set_correlation_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  correlation_id_ = value;
}
inline void VehicleMessageHeader::set_correlation_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_correlation_id(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.VehicleMessageHeader.correlation_id)
}

// string vehicle_id = 3;
inline void VehicleMessageHeader::clear_vehicle_id() {
  vehicle_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& VehicleMessageHeader::vehicle_id() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
  return _internal_vehicle_id();
}
inline void VehicleMessageHeader::set_vehicle_id(const std::string& value) {
  _internal_set_vehicle_id(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
}
inline std::string* VehicleMessageHeader::mutable_vehicle_id() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
  return _internal_mutable_vehicle_id();
}
inline const std::string& VehicleMessageHeader::_internal_vehicle_id() const {
  return vehicle_id_.GetNoArena();
}
inline void VehicleMessageHeader::_internal_set_vehicle_id(const std::string& value) {
  
  vehicle_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void VehicleMessageHeader::set_vehicle_id(std::string&& value) {
  
  vehicle_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
}
inline void VehicleMessageHeader::set_vehicle_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  vehicle_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
}
inline void VehicleMessageHeader::set_vehicle_id(const char* value, size_t size) {
  
  vehicle_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
}
inline std::string* VehicleMessageHeader::_internal_mutable_vehicle_id() {
  
  return vehicle_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* VehicleMessageHeader::release_vehicle_id() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
  
  return vehicle_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void VehicleMessageHeader::set_allocated_vehicle_id(std::string* vehicle_id) {
  if (vehicle_id != nullptr) {
    
  } else {
    
  }
  vehicle_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vehicle_id);
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.VehicleMessageHeader.vehicle_id)
}

// int64 message_timestamp = 4;
inline void VehicleMessageHeader::clear_message_timestamp() {
  message_timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 VehicleMessageHeader::_internal_message_timestamp() const {
  return message_timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 VehicleMessageHeader::message_timestamp() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.VehicleMessageHeader.message_timestamp)
  return _internal_message_timestamp();
}
inline void VehicleMessageHeader::_internal_set_message_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  message_timestamp_ = value;
}
inline void VehicleMessageHeader::set_message_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_message_timestamp(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.VehicleMessageHeader.message_timestamp)
}

// double protocol_version = 5;
inline void VehicleMessageHeader::clear_protocol_version() {
  protocol_version_ = 0;
}
inline double VehicleMessageHeader::_internal_protocol_version() const {
  return protocol_version_;
}
inline double VehicleMessageHeader::protocol_version() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.VehicleMessageHeader.protocol_version)
  return _internal_protocol_version();
}
inline void VehicleMessageHeader::_internal_set_protocol_version(double value) {
  
  protocol_version_ = value;
}
inline void VehicleMessageHeader::set_protocol_version(double value) {
  _internal_set_protocol_version(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.VehicleMessageHeader.protocol_version)
}

// .com.vehicle.messages.lat_long location = 6;
inline bool VehicleMessageHeader::_internal_has_location() const {
  return this != internal_default_instance() && location_ != nullptr;
}
inline bool VehicleMessageHeader::has_location() const {
  return _internal_has_location();
}
inline void VehicleMessageHeader::clear_location() {
  if (GetArenaNoVirtual() == nullptr && location_ != nullptr) {
    delete location_;
  }
  location_ = nullptr;
}
inline const ::com::vehicle::messages::lat_long& VehicleMessageHeader::_internal_location() const {
  const ::com::vehicle::messages::lat_long* p = location_;
  return p != nullptr ? *p : *reinterpret_cast<const ::com::vehicle::messages::lat_long*>(
      &::com::vehicle::messages::_lat_long_default_instance_);
}
inline const ::com::vehicle::messages::lat_long& VehicleMessageHeader::location() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.VehicleMessageHeader.location)
  return _internal_location();
}
inline ::com::vehicle::messages::lat_long* VehicleMessageHeader::release_location() {
  // @@protoc_insertion_point(field_release:com.vehicle.messages.VehicleMessageHeader.location)
  
  ::com::vehicle::messages::lat_long* temp = location_;
  location_ = nullptr;
  return temp;
}
inline ::com::vehicle::messages::lat_long* VehicleMessageHeader::_internal_mutable_location() {
  
  if (location_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::vehicle::messages::lat_long>(GetArenaNoVirtual());
    location_ = p;
  }
  return location_;
}
inline ::com::vehicle::messages::lat_long* VehicleMessageHeader::mutable_location() {
  // @@protoc_insertion_point(field_mutable:com.vehicle.messages.VehicleMessageHeader.location)
  return _internal_mutable_location();
}
inline void VehicleMessageHeader::set_allocated_location(::com::vehicle::messages::lat_long* location) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete location_;
  }
  if (location) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      location = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, location, submessage_arena);
    }
    
  } else {
    
  }
  location_ = location;
  // @@protoc_insertion_point(field_set_allocated:com.vehicle.messages.VehicleMessageHeader.location)
}

// -------------------------------------------------------------------

// lat_long

// double latitude = 1;
inline void lat_long::clear_latitude() {
  latitude_ = 0;
}
inline double lat_long::_internal_latitude() const {
  return latitude_;
}
inline double lat_long::latitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.lat_long.latitude)
  return _internal_latitude();
}
inline void lat_long::_internal_set_latitude(double value) {
  
  latitude_ = value;
}
inline void lat_long::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.lat_long.latitude)
}

// double longitude = 2;
inline void lat_long::clear_longitude() {
  longitude_ = 0;
}
inline double lat_long::_internal_longitude() const {
  return longitude_;
}
inline double lat_long::longitude() const {
  // @@protoc_insertion_point(field_get:com.vehicle.messages.lat_long.longitude)
  return _internal_longitude();
}
inline void lat_long::_internal_set_longitude(double value) {
  
  longitude_ = value;
}
inline void lat_long::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:com.vehicle.messages.lat_long.longitude)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace vehicle
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_V2C_2fVehicleMessageHeader_2eproto
