// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: V2C/VehicleMessageHeader.proto

package com.vehicle.messages;

public final class VehicleMessageHeaderOuterClass {
  private VehicleMessageHeaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VehicleMessageHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.vehicle.messages.VehicleMessageHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique Application message_id. When initiated from channels like Mobile or API Gateways this should persist all the way to the vehilce, returning as a correlation id.
     * </pre>
     *
     * <code>int32 message_id = 1;</code>
     * @return The messageId.
     */
    int getMessageId();

    /**
     * <pre>
     * For request/response and other multi-message patterns this should be populated with the message_id of the first message in the chain.
     * </pre>
     *
     * <code>int32 correlation_id = 2;</code>
     * @return The correlationId.
     */
    int getCorrelationId();

    /**
     * <pre>
     * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
     * </pre>
     *
     * <code>string vehicle_id = 3;</code>
     * @return The vehicleId.
     */
    java.lang.String getVehicleId();
    /**
     * <pre>
     * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
     * </pre>
     *
     * <code>string vehicle_id = 3;</code>
     * @return The bytes for vehicleId.
     */
    com.google.protobuf.ByteString
        getVehicleIdBytes();

    /**
     * <pre>
     * EPOCH timestamp when the message was created
     * </pre>
     *
     * <code>int64 message_timestamp = 4;</code>
     * @return The messageTimestamp.
     */
    long getMessageTimestamp();

    /**
     * <pre>
     * version of the protocol schema/data model being used.
     * </pre>
     *
     * <code>double protocol_version = 5;</code>
     * @return The protocolVersion.
     */
    double getProtocolVersion();

    /**
     * <pre>
     * GNSS latitude and longtitude 
     * </pre>
     *
     * <code>.com.vehicle.messages.lat_long location = 6;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <pre>
     * GNSS latitude and longtitude 
     * </pre>
     *
     * <code>.com.vehicle.messages.lat_long location = 6;</code>
     * @return The location.
     */
    com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long getLocation();
    /**
     * <pre>
     * GNSS latitude and longtitude 
     * </pre>
     *
     * <code>.com.vehicle.messages.lat_long location = 6;</code>
     */
    com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder getLocationOrBuilder();
  }
  /**
   * <pre>
   * # Vehicle Message Header
   * This message defines an application message header for messages past across the system. This is useful because the standard MQTT message headers are typically local to the broker of the system, so while the MQTT headers 
   * are useful for QoS assurances and message debugging they do not necessarily correlate the messages to the 
   * services deeper in the vehicle or the cloud services. 
   * ## Message Orchestration
   * ![HeaderMessage.puml](build/resources/main/V2C/images/HeaderMessage.png)
   * ## MQTT Topic Design
   * | Direction        | Subscribe Topic | Publish Topic | 
   * | -----------      | -----           | --------      |
   * | Vehicle to Cloud | No Topic        | No Topic      |
   * | -----------      | -----           | --------      |
   * | Cloud to Vehicle | No Topic        |  No Topic     |
   * </pre>
   *
   * Protobuf type {@code com.vehicle.messages.VehicleMessageHeader}
   */
  public  static final class VehicleMessageHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.vehicle.messages.VehicleMessageHeader)
      VehicleMessageHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VehicleMessageHeader.newBuilder() to construct.
    private VehicleMessageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VehicleMessageHeader() {
      vehicleId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VehicleMessageHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleMessageHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 16: {

              correlationId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              vehicleId_ = s;
              break;
            }
            case 32: {

              messageTimestamp_ = input.readInt64();
              break;
            }
            case 41: {

              protocolVersion_ = input.readDouble();
              break;
            }
            case 50: {
              com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_VehicleMessageHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_VehicleMessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.class, com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.Builder.class);
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <pre>
     * Unique Application message_id. When initiated from channels like Mobile or API Gateways this should persist all the way to the vehilce, returning as a correlation id.
     * </pre>
     *
     * <code>int32 message_id = 1;</code>
     * @return The messageId.
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int CORRELATION_ID_FIELD_NUMBER = 2;
    private int correlationId_;
    /**
     * <pre>
     * For request/response and other multi-message patterns this should be populated with the message_id of the first message in the chain.
     * </pre>
     *
     * <code>int32 correlation_id = 2;</code>
     * @return The correlationId.
     */
    public int getCorrelationId() {
      return correlationId_;
    }

    public static final int VEHICLE_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object vehicleId_;
    /**
     * <pre>
     * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
     * </pre>
     *
     * <code>string vehicle_id = 3;</code>
     * @return The vehicleId.
     */
    public java.lang.String getVehicleId() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
     * </pre>
     *
     * <code>string vehicle_id = 3;</code>
     * @return The bytes for vehicleId.
     */
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_TIMESTAMP_FIELD_NUMBER = 4;
    private long messageTimestamp_;
    /**
     * <pre>
     * EPOCH timestamp when the message was created
     * </pre>
     *
     * <code>int64 message_timestamp = 4;</code>
     * @return The messageTimestamp.
     */
    public long getMessageTimestamp() {
      return messageTimestamp_;
    }

    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 5;
    private double protocolVersion_;
    /**
     * <pre>
     * version of the protocol schema/data model being used.
     * </pre>
     *
     * <code>double protocol_version = 5;</code>
     * @return The protocolVersion.
     */
    public double getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int LOCATION_FIELD_NUMBER = 6;
    private com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long location_;
    /**
     * <pre>
     * GNSS latitude and longtitude 
     * </pre>
     *
     * <code>.com.vehicle.messages.lat_long location = 6;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <pre>
     * GNSS latitude and longtitude 
     * </pre>
     *
     * <code>.com.vehicle.messages.lat_long location = 6;</code>
     * @return The location.
     */
    public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long getLocation() {
      return location_ == null ? com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.getDefaultInstance() : location_;
    }
    /**
     * <pre>
     * GNSS latitude and longtitude 
     * </pre>
     *
     * <code>.com.vehicle.messages.lat_long location = 6;</code>
     */
    public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (correlationId_ != 0) {
        output.writeInt32(2, correlationId_);
      }
      if (!getVehicleIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, vehicleId_);
      }
      if (messageTimestamp_ != 0L) {
        output.writeInt64(4, messageTimestamp_);
      }
      if (protocolVersion_ != 0D) {
        output.writeDouble(5, protocolVersion_);
      }
      if (location_ != null) {
        output.writeMessage(6, getLocation());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (correlationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, correlationId_);
      }
      if (!getVehicleIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, vehicleId_);
      }
      if (messageTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, messageTimestamp_);
      }
      if (protocolVersion_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, protocolVersion_);
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getLocation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader)) {
        return super.equals(obj);
      }
      com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader other = (com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (getCorrelationId()
          != other.getCorrelationId()) return false;
      if (!getVehicleId()
          .equals(other.getVehicleId())) return false;
      if (getMessageTimestamp()
          != other.getMessageTimestamp()) return false;
      if (java.lang.Double.doubleToLongBits(getProtocolVersion())
          != java.lang.Double.doubleToLongBits(
              other.getProtocolVersion())) return false;
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCorrelationId();
      hash = (37 * hash) + VEHICLE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleId().hashCode();
      hash = (37 * hash) + MESSAGE_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageTimestamp());
      hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getProtocolVersion()));
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * # Vehicle Message Header
     * This message defines an application message header for messages past across the system. This is useful because the standard MQTT message headers are typically local to the broker of the system, so while the MQTT headers 
     * are useful for QoS assurances and message debugging they do not necessarily correlate the messages to the 
     * services deeper in the vehicle or the cloud services. 
     * ## Message Orchestration
     * ![HeaderMessage.puml](build/resources/main/V2C/images/HeaderMessage.png)
     * ## MQTT Topic Design
     * | Direction        | Subscribe Topic | Publish Topic | 
     * | -----------      | -----           | --------      |
     * | Vehicle to Cloud | No Topic        | No Topic      |
     * | -----------      | -----           | --------      |
     * | Cloud to Vehicle | No Topic        |  No Topic     |
     * </pre>
     *
     * Protobuf type {@code com.vehicle.messages.VehicleMessageHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.vehicle.messages.VehicleMessageHeader)
        com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_VehicleMessageHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_VehicleMessageHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.class, com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.Builder.class);
      }

      // Construct using com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        correlationId_ = 0;

        vehicleId_ = "";

        messageTimestamp_ = 0L;

        protocolVersion_ = 0D;

        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_VehicleMessageHeader_descriptor;
      }

      @java.lang.Override
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader getDefaultInstanceForType() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader build() {
        com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader buildPartial() {
        com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader result = new com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader(this);
        result.messageId_ = messageId_;
        result.correlationId_ = correlationId_;
        result.vehicleId_ = vehicleId_;
        result.messageTimestamp_ = messageTimestamp_;
        result.protocolVersion_ = protocolVersion_;
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader) {
          return mergeFrom((com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader other) {
        if (other == com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getCorrelationId() != 0) {
          setCorrelationId(other.getCorrelationId());
        }
        if (!other.getVehicleId().isEmpty()) {
          vehicleId_ = other.vehicleId_;
          onChanged();
        }
        if (other.getMessageTimestamp() != 0L) {
          setMessageTimestamp(other.getMessageTimestamp());
        }
        if (other.getProtocolVersion() != 0D) {
          setProtocolVersion(other.getProtocolVersion());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <pre>
       * Unique Application message_id. When initiated from channels like Mobile or API Gateways this should persist all the way to the vehilce, returning as a correlation id.
       * </pre>
       *
       * <code>int32 message_id = 1;</code>
       * @return The messageId.
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <pre>
       * Unique Application message_id. When initiated from channels like Mobile or API Gateways this should persist all the way to the vehilce, returning as a correlation id.
       * </pre>
       *
       * <code>int32 message_id = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique Application message_id. When initiated from channels like Mobile or API Gateways this should persist all the way to the vehilce, returning as a correlation id.
       * </pre>
       *
       * <code>int32 message_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int correlationId_ ;
      /**
       * <pre>
       * For request/response and other multi-message patterns this should be populated with the message_id of the first message in the chain.
       * </pre>
       *
       * <code>int32 correlation_id = 2;</code>
       * @return The correlationId.
       */
      public int getCorrelationId() {
        return correlationId_;
      }
      /**
       * <pre>
       * For request/response and other multi-message patterns this should be populated with the message_id of the first message in the chain.
       * </pre>
       *
       * <code>int32 correlation_id = 2;</code>
       * @param value The correlationId to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationId(int value) {
        
        correlationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For request/response and other multi-message patterns this should be populated with the message_id of the first message in the chain.
       * </pre>
       *
       * <code>int32 correlation_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorrelationId() {
        
        correlationId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object vehicleId_ = "";
      /**
       * <pre>
       * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
       * </pre>
       *
       * <code>string vehicle_id = 3;</code>
       * @return The vehicleId.
       */
      public java.lang.String getVehicleId() {
        java.lang.Object ref = vehicleId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vehicleId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
       * </pre>
       *
       * <code>string vehicle_id = 3;</code>
       * @return The bytes for vehicleId.
       */
      public com.google.protobuf.ByteString
          getVehicleIdBytes() {
        java.lang.Object ref = vehicleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vehicleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
       * </pre>
       *
       * <code>string vehicle_id = 3;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vehicleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
       * </pre>
       *
       * <code>string vehicle_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        
        vehicleId_ = getDefaultInstance().getVehicleId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * this can be any unique identifier for the vehicle, we recommend using the fingerprint on the client's unique x.509 certificate. 
       * </pre>
       *
       * <code>string vehicle_id = 3;</code>
       * @param value The bytes for vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vehicleId_ = value;
        onChanged();
        return this;
      }

      private long messageTimestamp_ ;
      /**
       * <pre>
       * EPOCH timestamp when the message was created
       * </pre>
       *
       * <code>int64 message_timestamp = 4;</code>
       * @return The messageTimestamp.
       */
      public long getMessageTimestamp() {
        return messageTimestamp_;
      }
      /**
       * <pre>
       * EPOCH timestamp when the message was created
       * </pre>
       *
       * <code>int64 message_timestamp = 4;</code>
       * @param value The messageTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTimestamp(long value) {
        
        messageTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * EPOCH timestamp when the message was created
       * </pre>
       *
       * <code>int64 message_timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageTimestamp() {
        
        messageTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private double protocolVersion_ ;
      /**
       * <pre>
       * version of the protocol schema/data model being used.
       * </pre>
       *
       * <code>double protocol_version = 5;</code>
       * @return The protocolVersion.
       */
      public double getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <pre>
       * version of the protocol schema/data model being used.
       * </pre>
       *
       * <code>double protocol_version = 5;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(double value) {
        
        protocolVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version of the protocol schema/data model being used.
       * </pre>
       *
       * <code>double protocol_version = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        
        protocolVersion_ = 0D;
        onChanged();
        return this;
      }

      private com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long location_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder> locationBuilder_;
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       * @return The location.
       */
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      public Builder setLocation(com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      public Builder setLocation(
          com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      public Builder mergeLocation(com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.getDefaultInstance() : location_;
        }
      }
      /**
       * <pre>
       * GNSS latitude and longtitude 
       * </pre>
       *
       * <code>.com.vehicle.messages.lat_long location = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.vehicle.messages.VehicleMessageHeader)
    }

    // @@protoc_insertion_point(class_scope:com.vehicle.messages.VehicleMessageHeader)
    private static final com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader();
    }

    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehicleMessageHeader>
        PARSER = new com.google.protobuf.AbstractParser<VehicleMessageHeader>() {
      @java.lang.Override
      public VehicleMessageHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleMessageHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VehicleMessageHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleMessageHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vehicle.messages.VehicleMessageHeaderOuterClass.VehicleMessageHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface lat_longOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.vehicle.messages.lat_long)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * GNSS latitude
     * </pre>
     *
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <pre>
     * GNSS longitude
     * </pre>
     *
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code com.vehicle.messages.lat_long}
   */
  public  static final class lat_long extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.vehicle.messages.lat_long)
      lat_longOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use lat_long.newBuilder() to construct.
    private lat_long(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private lat_long() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new lat_long();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private lat_long(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              latitude_ = input.readDouble();
              break;
            }
            case 17: {

              longitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_lat_long_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_lat_long_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.class, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <pre>
     * GNSS latitude
     * </pre>
     *
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <pre>
     * GNSS longitude
     * </pre>
     *
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0D) {
        output.writeDouble(1, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long)) {
        return super.equals(obj);
      }
      com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long other = (com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long) obj;

      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.vehicle.messages.lat_long}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.vehicle.messages.lat_long)
        com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_longOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_lat_long_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_lat_long_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.class, com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.Builder.class);
      }

      // Construct using com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitude_ = 0D;

        longitude_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.internal_static_com_vehicle_messages_lat_long_descriptor;
      }

      @java.lang.Override
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long getDefaultInstanceForType() {
        return com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.getDefaultInstance();
      }

      @java.lang.Override
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long build() {
        com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long buildPartial() {
        com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long result = new com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long) {
          return mergeFrom((com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long other) {
        if (other == com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double latitude_ ;
      /**
       * <pre>
       * GNSS latitude
       * </pre>
       *
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       * GNSS latitude
       * </pre>
       *
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GNSS latitude
       * </pre>
       *
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <pre>
       * GNSS longitude
       * </pre>
       *
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       * GNSS longitude
       * </pre>
       *
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GNSS longitude
       * </pre>
       *
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.vehicle.messages.lat_long)
    }

    // @@protoc_insertion_point(class_scope:com.vehicle.messages.lat_long)
    private static final com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long();
    }

    public static com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<lat_long>
        PARSER = new com.google.protobuf.AbstractParser<lat_long>() {
      @java.lang.Override
      public lat_long parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new lat_long(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<lat_long> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<lat_long> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vehicle.messages.VehicleMessageHeaderOuterClass.lat_long getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_messages_VehicleMessageHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_messages_VehicleMessageHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vehicle_messages_lat_long_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vehicle_messages_lat_long_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036V2C/VehicleMessageHeader.proto\022\024com.ve" +
      "hicle.messages\"\275\001\n\024VehicleMessageHeader\022" +
      "\022\n\nmessage_id\030\001 \001(\005\022\026\n\016correlation_id\030\002 " +
      "\001(\005\022\022\n\nvehicle_id\030\003 \001(\t\022\031\n\021message_times" +
      "tamp\030\004 \001(\003\022\030\n\020protocol_version\030\005 \001(\001\0220\n\010" +
      "location\030\006 \001(\0132\036.com.vehicle.messages.la" +
      "t_long\"/\n\010lat_long\022\020\n\010latitude\030\001 \001(\001\022\021\n\t" +
      "longitude\030\002 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vehicle_messages_VehicleMessageHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vehicle_messages_VehicleMessageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_messages_VehicleMessageHeader_descriptor,
        new java.lang.String[] { "MessageId", "CorrelationId", "VehicleId", "MessageTimestamp", "ProtocolVersion", "Location", });
    internal_static_com_vehicle_messages_lat_long_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_vehicle_messages_lat_long_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vehicle_messages_lat_long_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
